### ISSUE TITLE
possible type: blessedCaTherineOfSaintAugustineVirgin

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#15]
I think `blessedCaTherineOfSaintAugustineVirgin` key should be renamed to `blessedCatherineOfSaintAugustineVirgin`. Notice the lower-cased `t` in `Catherine`.

**Comment by pejulian** [comment]
Hi @tukusejssirs ,

Thanks for spotting out the typo!
Fix is now added to the `romcal-es6` branch.
