### ISSUE TITLE
typo in `romcal-es6/README.MD`: change `even thought` to `even though`

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#19]
I found a typo in the following paragraph:

data: An object that holds additional information about the celebration
- prioritized: A optional boolean that when true, gives the celebration higher priority over another coinciding celebration **_even thought_** that celebration has a higher ranking type. This flag should be used with caution.

**Comment by pejulian** [comment]
Hi @tukusejssirs,

Thanks for the continued list of issues/improvements raised.
I have some time to quickly try close a few of them today.

God bless!
