### ISSUE TITLE
Can't Query Single Date?

### ISSUE THREAD

**Issue by sjlehn** [pejulian/romcal#190]
I'm trying to pull the calendar for a particular date (e.g. today's date). However, it seems that something like this:
```js
Romcal.calendarFor({
     country: 'unitedStates',
     locale: 'en',
     christmastideEnds: 'o',
     epiphanyOnJan6: false,
     corpusChristiOnThursday: false,
     ascensionOnSunday: true,
     query: {
         day: now.getDay(), // 0 - Sunday, 6 - Saturday (week beginning with Sunday)
         month: now.getMonth() // 0 - Jan, 11 - Dec (month beginning with Jan)
     }
 },
true);
```

where now is today's date, gives me every Tuesday in the month of April. It seems like the only way to get the current date is to calculate the current day # (0-364), and then access the full calendar array that way. It seems like there should be a way to get the calendar entry for a single known date. Am I missing something?

**Comment by emagnier** [comment]
Currently the romcal API have some naming and features not very obvious (we are working on it). Here this `day` property is used to filter dates by day of weeks.

If you want the date for today (or any specific day), in the meantime you will have to manually filter the results data to find it.

**Comment by emagnier** [comment]
Also I do not recommend you to calculate the current day (0-364) to get the corresponding one, since the future releases of romcal will be able to output multiple celebrations for one day, when it's accurate.

Something like this might do what you need:

```
const dates = Romcal.calendarFor({
     country: 'unitedStates',
     locale: 'en',
     christmastideEnds: 'o',
     epiphanyOnJan6: false,
     corpusChristiOnThursday: false,
     ascensionOnSunday: true
 },
true);

todayDates = dates.filter((item) => {
  const today = new Date();
  const date = new Date(item.date);
  return (
    date.getDate() === today.getDate() &&
    date.getMonth() === today.getMonth() &&
    date.getFullYear() === today.getFullYear()
  );
});

console.log(todayDates[0]);
```

**Comment by sjlehn** [comment]
Thanks! I'll have to switch the lookup to this the next time I get into that code.

**Comment by emagnier** [comment]
👍 

Feel free to continue the discussion, or open another issue for anything else.

**Comment by sjlehn** [comment]
Ok, I got this working, but I had to make one change: `const date = new Date(item.date);` produces an invalid date error.

I switched it to `item.moment.toDate()` and it works beautifully.
