### ISSUE TITLE
Optional memoria of St Faustina celebrated world-wide

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#191]
Today, pope Francis issue a decree that the optional memoria of St Faustina is to be celebrated world-wide (i.e. in `general`) on 5 October. ([Vatican News](https://www.vaticannews.va/en/pope/news/2020-05/saint-faustina-kowalska-roman-calendar-universal-feast.html), [Catholic News Agency](https://www.catholicnewsagency.com/news/pope-francis-adds-st-faustina-kowalskas-feast-to-roman-calendar-83069)).

I could change this in romcal, but point me to the branch on which which I should base this commit. Thanks. :)

**Comment by emagnier** [comment]
You can do it in the `_F-TypeScript` branch (this branch is close to be released in the `dev` branch). Thank you!
