### ISSUE TITLE
Make GitHub description say e.g. "Roman Rite of the Catholic Church" instead of "Catholic Rite"

### ISSUE THREAD

**Issue by electrodude** [pejulian/romcal#193]
The current GitHub project description is:
> Generates the General Roman Calendar used in the Catholic Rite. 

There is no such thing as the "Catholic Rite".  All of the rites used within the Catholic Church -- the Roman Rite, a few variations on Latin Rite such as the Ambrosian and Dominican Rites, and all of eastern rites -- are Catholic rites, and many of them have their own calendars.

It should instead say something like "the Roman Rite of the Catholic Church".

**Comment by emagnier** [comment]
You are right! 
What do you think @pejulian ? I don't have the right to edit this headline.

**Comment by emagnier** [comment]
Thank you! It's now updated to:

> Generates the liturgical calendar of the Catholic Church used by the Roman Rite.

And let me know if the wording could be improved, English is not my primary language 😉

**Comment by tukusejssirs** [comment]
@emagnier, how about to get inspired by [Wiki: GRC article short description](https://en.wikipedia.org/wiki/Special:MobileDiff/1027772738?diffmode=source)?

> Liturgical calendar of Saints' Days for the ordinary form of the Roman Rite (Roman Catholic Church)

Like: _Generates liturgical calendars of the Roman Rite of the Roman Catholic Church_.

I think _calendars_ should plural, as we generate different cals by country or language.

I personally wouldn’t include _ordinary form_. We also might place _Roman Catholic Church_ in brackets or even remove it altogether, but for people less learned in the liturgy, it might be useful to keep it.

And in English, there is no such thing as implicit/silent subject, therefore it sounds strange and is grammatically incorrect without `romcal` at the the beginning. I know in code we do it that way a llt, but in user-facing docs I don’t think it is a valid reason to remove the subject. That said I let you decide on this. :wink:

What do you think?

**Comment by emagnier** [comment]
> Generates liturgical calendars of the Roman Rite of the Roman Catholic Church.

This is a good proposition. I've updated the repo description.

We still have to update the headline in the main readme.md

**Comment by tukusejssirs** [comment]
> We still have to update the headline in the main readme.md

Should I create a PR for that?

**Comment by emagnier** [comment]
Yes please 😄
