### ISSUE TITLE
Use Roman numarals for day number, weekday number and week number

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#195]
I am currently in the middle of the Latin localisation (`la.ts`) and in Latin, we usually use Roman numerals for:
- day number (e.g. `Die XXIV decembris` = 24 December);
- weekday number (e.g. `Feria II` = Monday);
- week number (e.g. `hebdomada III` = week 3).

Now, `dayjs` currently does not support Latin and I don’t feel like I will be the one to create the `dayjs` config for Latin.

I have no idea what would be the best way implement this.

**Comment by emagnier** [comment]
For the time being we could continue to use arabic numbers, even with a latin translation.
I think Dayjs will never add support for roman numbers, and I'm also not too thrilled by hacking the localisation codebase to get roman numbers specifically in latin.

Someday, we could eventually add a global helper that would try to convert any arabic numbers from a string to roman numbers. This could be enabled on a global option like `romaniseNumbers: true | false` (false by default).

**Comment by tukusejssirs** [comment]
I am in the middle of the process of adding `la.js` locale to dayjs at Roman numerals are the least problem to me, as dayjs allows adding custom fumctions to the locales, therefore I’ll add the [`romanise()`](https://stackoverflow.com/a/9083076/3408342) function. :smiley:

**Update:** But that won’t solve the (seasonal) week number.

**Comment by emagnier** [comment]
FYI romcal `v3` now provide better tooling to write date in Latin, including Roman numerals and ordinals.
