### ISSUE TITLE
Date romanisation (day of month, month number, year)

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#196]
Related: #195, iamkun/dayjs#961, iamkun/dayjs#966

---

As `dayjs` does not support Latin (yet), I have no idea how could we localise Latin weekday names other that use our own localisation files, but that would be useful only when we would localise them each and every language (which from my point of view might be a solution).

Anyway, just for the reference, here’s the list of Latin weekday names with their English counter-parts:
- `Sunday`: `Dominica`;
- `Monday`: `Feria secunda` (alt: `Feria II`);
- `Tuesday`: `Feria tertia` (alt: `Feria III`);
- `Wednesday`: `Feria quarta` (alt: `Feria IV`);
- `Thursday`: `Feria quinta` (alt: `Feria V`);
- `Friday`: `Feria sexta` (alt: `Feria VI`);
- `Saturday`: `Sabbato`.

**Comment by emagnier** [comment]
I don't know what is the effort for that, but the best scenario would be first, to submit a new Latin localisation on the dayjs project, so then we could use this locale as any other locales with dayjs on romcal.

**Comment by tukusejssirs** [comment]
Would you like to create a PR at `dayjs`? I don’t feel comfortable with it, as I have tried to deal with #186 in `dayjs` repo, only to find out that they test the output of `dayjs` with the output of Moment, therefore the issue is in Moment too ... where I had some loong conversion (without any resolution) about the rules and either nobody can or nobody wish (or both) to change the issue. I personally would opt for using in house localisation for everything, but I know that you wish not to burden ourselves (esp yourself) with anything that is not necessary.

**Comment by emagnier** [comment]
I can hardly find time for romcal. So no, I definitely don't have the time for that for the time being 😄 
And dayjs (like moment.js) work already very well for date / time localisations, so no need to reinvent the wheel.

Take a look here: https://github.com/iamkun/dayjs/tree/dev/src/locale, maybe it just need a new la.js in this directory.

**Comment by tukusejssirs** [comment]
> And dayjs (like moment.js) work already very well for date / time localisations, so no need to reinvent the wheel.

From my point view, it _nearly always_ work, but it is not 100 % correct for Slovak, which bother me quite much.

> Take a look here: https://github.com/iamkun/dayjs/tree/dev/src/locale, maybe it just need a new la.js in this directory.

True, only `la.js` is needed in `day.js` and another one in Moment, as `day.js` compares its output with the Moment output.

**Comment by tukusejssirs** [comment]
@emagnier, I am working on this at `dayjs` (see iamkun/dayjs#961 and iamkun/dayjs#966). One final thing that still does not work is the year romanisation.

I need to create a [`dayjs` plugin](https://day.js.org/docs/en/plugin/plugin) for that. I could modify the code from [`buddhistEra`](https://github.com/iamkun/dayjs/blob/dev/src/plugin/buddhistEra/index.js) for this, but there is one potential issue with that: it does not _replaces_ the year (e.g. `YY` or `YYYY`) the the year of the Buddhist Era, however, _adds_ additional date format `BB`/`BBBB` (for romanised year, we could use something like `RR` or `RRRR`).

My question is if that is okay from romcal point of view. If it is okay with you, we might want to add romcal option for this (e.g. `romanizeYears`) with default value being `false` and we would set this per locale. That, however, would require creating locale-specific settings (presumably in the l10n files, like `en.ts`), which we currently lack. On the other hand, it might be a good thing to introduce the locale-specific settings. :smiley:

I still talk with [@iamkun](https://github.com/iamkun) if there is a way to _replace_ the year in the `dayjs` object via plugin, however, I suspect that it is not possible, as it (1) changes the data type from int to string; (2) it would most probably ruin some processes/operations within the core of `dayjs`.

**Update:** [It looks like we won’t have the `romanisation` plugin in the official plugin list within `dayjs`.](https://github.com/iamkun/dayjs/issues/961#issuecomment-694954147) I think we need to create such a plugin either in a separate repo or within romcal codebase. As it is just a small addition (in a sense: just an extension), I think we should keep it within romcal codebase. FYI, [here](https://github.com/iamkun/dayjs/issues/961#issuecomment-694883440)’s my current _non-working_ version of `romanisation` plugin.

**Comment by tukusejssirs** [comment]
@emagnier, just to wrap it up: the Latin locale will be added to `dayjs` (when I finish adding the tests), however, it won’t romanise the year.

As for the romanisation of year, I see two possible solutions:

1. use custom plugin in `dayjs`:
   - we could either keep it in a separate repo or within romcal codebase;
   - we need to maintain it;
   - it could look like the `buddhistEra` plugin (which is an official one);

2. keep the functionality in romcal:
   - we could create a romcal plugin or simply keep it within romcal codebase;
   - we could provide a romcal option to romanise year (or month or day of month; all of these three options are used in different locales);
   - I think this solution is much better, because it gives us more control;
   - I think we should create _locale options_ (as we have _calendar options_) and romanisation could be one of them (of course, for now we could keep the romanisation option in the general/calendar options).

**Comment by emagnier** [comment]
FYI romcal `v3` now provide better tooling to write date in Latin, including Roman numerals and ordinals.

**Comment by tukusejssirs** [comment]
> FYI romcal `v3` now provide better tooling to write date in Latin, including Roman numerals and ordinals.

@emagnier, could you elaborate or provide a link to some docs please? How could a particular locale be configured to either use or not use year and/or month (as number) in Roman numerals? (Related/duplicate issue: #195; locale config related issue: #241).

**Comment by emagnier** [comment]
For example, the latest edition of the Italian missal use Roman numerals for weekdays & Sundays. 

To be closed to the missal, in romcal it's accomplished that way: https://github.com/romcal/romcal/blob/6d86fade3461c725bc03a738f6960dbb1d570930/lib/locales/it.ts#L26
