### ISSUE TITLE
Localise celebration rank names

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#197]
I my opinion, we should localise the celebration rank names too, like we do (in the TS branch) with the liturgical colours.

Just for reference, here are the Latin rank names with their respective English counter-parts:
- `solemnity`: `sollemnitas`;
- `Sunday`: `Dominica` (should this one be in the celebration ranks?);
- `Triduum`: `Triduum paschale`;
- `Holy Week`: `Hebdomadæ sanctæ`;
- `feast`: `festum`;
- `memorial`: `memoria`;
- `optional memorial`: `memoria ad libitum`;
- `commemoration`: `commemoratio`;
- `feria`: `feria`.

---

Sidenote: In [this project], they use `Dies liturgici primarii` (primary liturgical days) rank for:
- Sundays in the Advent, Lent (incl the Palm Sunday) and Eastertide;
- days in the Holy Week, incl the Triduum;
- the Pentecost Sunday;
- days in the Easter Octave;
- Ash Wednesday;
- Epiphany;
- Ascension of the Lord.

I think we use `celebrations` for approx the same celebrations, but in my opinion `celebrations` is a bit ambiguous name for these and `primary liturgical days` is IMHO more suitable.

**Comment by emagnier** [comment]
Someday, the rank management in Romcal should be closest to the paragraph **59** described in the [Universal Norms on the Liturgical Year and the General Roman Calendar](https://www.liturgyoffice.org.uk/Calendar/Info/GNLY.pdf).

This would require quite a lot of refactoring, but I hope it could happen someday.

**Comment by tukusejssirs** [comment]
That would be awesome!

However, this issue deals with the _localisation_, not the _implementation_. I don’t think that it would be too much work to implement the localisation of the celebration ranks.

**Comment by emagnier** [comment]
FYI, these localisation can be made in the `_F-TypeScript` branch.
It already contain translation for `en`, `fr`, `it`.

**Comment by tukusejssirs** [comment]
I’ve seen it yesterday. I’ll add Latin and Slovak localisation of the rank namew.

BTW, is there any reason why did you use first letter capitalisation (e.g. `Feria` in Italian)? I think they should be written all lowercase unless they are proper names / for grammatical reasons (e.g. `Sunday`).

**Comment by emagnier** [comment]
You are right, in lowercase it's better.

**Comment by tukusejssirs** [comment]
I think that if/when we will use ranks according to the UNLY, we should take a look at how they did it in `calendarium-romanum`; the rank names are in [this file](https://github.com/igneus/calendarium-romanum/blob/master/config/locales/en.yml#L59:L73). Copy-pasting the relevant part below.

```js
rank:
  '1_1': Easter triduum
  '1_2': Primary liturgical days
  '1_3': Solemnities in the General Calendar
  '1_4': Proper solemnities
  '2_5': Feasts of the Lord in the General Calendar
  '2_6': Unprivileged Sundays
  '2_7': Feasts of saints in the General Calendar
  '2_8': Proper feasts
  '2_9': Privileged ferials
  '3_10': Obligatory memorials in the General Calendar
  '3_11': Proper obligatory memorials
  '3_12': Optional memorials
  '3_13': Ferials
  '4_0': Commemorations
```

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
