### ISSUE TITLE
Add Saturday memorial of the Blessed Virgin Mary

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#198]
I believe I have raised this issue somewhere, but I could not find the issue.

We should add the Saturday memorial of the Blessed Virgin Mary on each Saturday of the Ordinary Time where there is either feria only, or one or more optional memorials. This should be done in the `general.ts` or the `celebrations.ts`, as this Memorial can be celebrated throughout the whole Church.

**Comment by tukusejssirs** [comment]
Just a note with localisations of the celebration name:
- `cs`: `Sobotní památka Panny Marie`.

**Comment by emagnier** [comment]
Could be related in some points to https://github.com/romcal/romcal/issues/135.

**Comment by tukusejssirs** [comment]
> Could be related in some points to #135.

We your issue (#135) better worded with some specific solutions.

In my opinion, when implemented, we could create something that would solve:
- the Saturday Memorial of BVM;
- the recurring celebrations (as you suggested in #135);
- celebration of a celebration multiple times in one year at specific dates (even on dates defined as on 33rd Sunday in the OT; see [#259 (comment)](https://github.com/romcal/romcal/pull/259#issuecomment-774687684)).

---

We could close this issue in favour of #135 if you think so. :wink:

**Comment by emagnier** [comment]
> We could close this issue in favour of #135 if you think so. 😉

Yes. Just provide use cases in #135 is enough.
