### ISSUE TITLE
Add test if all keys are used

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#203]
I suggest to add a test before committing (or at least before merging) to check if all the keys used in the calendars and `src/lib/celebrations.ts` are defined in the l10n files and also if all the keys defined in the l10n files are actually used.

The way I do it is as follows:

```bash
# Get list of all used l10n keys in all calendars
grep -hPo "^\s*key: '\K[^']+" src/calendars/* src/lib/Celebrations.ts | sed '/^aSampleCelebration[0-9]\+$\|^epiphany$\|^HOLY_WEEK$\|^holyWeek.season$\|^LENT$\|^lent.season$/d' | sort | uniq > cel_keys

# Get list of all keys in all l10n files
grep -hPo --exclude=index.ts "^\s+'*\K[^}': ]+(?='*:)" src/locales/* | sed '/^advent$\|^season$\|^$\|^feria$\|^sunday$\|^christmastide$\|^day$\|^octave$\|^epiphany$\|^before$\|^after$\|^ordinaryTime$\|^lent$\|^dayAfterAshWed$\|^holyWeek$\|^eastertide$\|^liturgicalColors$\|^GOLD$\|^GREEN$\|^PURPLE$\|^RED$\|^ROSE$\|^WHITE$\|^celebrations$\|^sanctoral$/d' | sort | uniq > all_keys

# Compare the to files (output should be empty if all keys are defined and no key defined is unused)
diff -y --suppress-common-lines all_keys cel_keys
```

**Comment by tukusejssirs** [comment]
Just a note that in bdb3fd3d386537a29bc3d69baaf7e36699dd9365 (current `HEAD` of PR #202), the output of the `diff` is as follows:

```bash
$ diff -y --suppress-common-lines all_keys cel_keys 
blessedIstvanSandorMartyr				      <
shroveMonday						      <
shroveTuesday						      <
```

That means that in that branch, we have three keys defined in the l10n files that are not used in any of the calendars. In the past I thought we should keep them, but now I think we should remove them. When needed, we might re-add them in the future.

**Comment by TobiTenno** [comment]
@tukusejssirs would you consider this covered by `npm run data:checks`?

<details> <summary>example of the "failing" output</summary>

<pre>
 ERR   Useless martyrology items:
       - agapitus_of_palestrina_martyr
       - christopher_of_anatolia_martyr
       - cyriacus_martyr
       - lawrence_justinian
       - mammes_of_caesarea_martyr
       - marcellinus_of_ancona_bishop
       - mary_mother_of_hope
       - miltiades_pope
       - pelagia_the_penitent_virgin
       - romanus_martyr
       - thecla_of_iconium_virgin
       - theodore_stratelates

 ERR   Useless localized 'el' items:
       names:
       - dedication_of_the_basilica_of_our_lady_of_the_snows_tinos_grece
       - dedication_of_the_cathedral_of_saint_dionysius_athens
       - lydia_of_philippi_first_european_christian
       - our_lady_of_angels
       - timothy_of_ephesus_and_titus_the_first_bishop_of_crete_bishops
       - twelve_apostles
       - zechariah_and_elizabeth_parents_of_john_the_baptist

 ERR   Useless localized 'en-gb' items:
       names:
       - dedication_of_the_basilica_of_our_lady_of_the_snows_tinos_grece
       - dedication_of_the_cathedral_of_saint_dionysius_athens
       - lydia_of_philippi_first_european_christian
       - timothy_of_ephesus_and_titus_the_first_bishop_of_crete_bishops
       - twelve_apostles
       - zechariah_and_elizabeth_parents_of_john_the_baptist

 ERR   Useless localized 'en-ie' items:
       names:
       - dedication_of_the_basilica_of_our_lady_of_the_snows_tinos_grece
       - dedication_of_the_cathedral_of_saint_dionysius_athens
       - lydia_of_philippi_first_european_christian
       - timothy_of_ephesus_and_titus_the_first_bishop_of_crete_bishops
       - twelve_apostles
       - zechariah_and_elizabeth_parents_of_john_the_baptist

 ERR   Useless localized 'en' items:
       names:
       - dedication_of_the_basilica_of_our_lady_of_the_snows_tinos_grece
       - dedication_of_the_cathedral_of_saint_dionysius_athens
       - lydia_of_philippi_first_european_christian
       - timothy_of_ephesus_and_titus_the_first_bishop_of_crete_bishops
       - twelve_apostles
       - zechariah_and_elizabeth_parents_of_john_the_baptist

 WARN  Missing localized 'el' items for the Proper of Time and the General Roman Calendar:
       ranks:
       - optional_memorial
       names:
       - dedication_of_consecrated_churches
</pre>

</details>

if not, what else should we add?

**Comment by tukusejssirs** [comment]
Yeah, @TobiTenno, I think this issue is already implement using `data:checks`.

Thanks for bringing this up! :pray:
