### ISSUE TITLE
Define all celebrations celebrated in GRC in `general.ts`

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#210]
Currently, most of the celebrations are defined in `src/calendars/general.ts`, but some are defined in `src/lib/Celebrations.ts`. Moreover, the dates of celebration in `Celebrations.ts` are not defined there, but in `src/lib/Dates.ts`, which is mostly quite silly (all of the celebrations defined in `src/calendars/*.ts` have the dates defined within the celebration definition).

I suggest that the function (like the one in `_easter` constant) might be moved to some file (e.g. `src/utils/dates.ts`), which (fhe function) would be sourced in `general.ts`. However, I think that they all could be simply moved to `general.ts`.

Of course, we need a flag/option/parameter (whatever you call it) in the celebration definition, that would make it impossible to change some celebrations (like Easter or Christmas), or even better: use the celebration ranking from the [Table of Liturgical Dates](https://www.dio.org/uploads/files/Worship/Liturgical_Year_and_Calendar/Table_of_Liturgical_Days.pdf) from the General Norms for the Liturgical Year and the Calendar.

Also, I think that the celebration definitions within a calendar (like `general.ts` or `en.ts`) should be sorted in two groups:

- fixed date celebrations:
   - celebrations, that have a fixed date;
   - these celebrations still might be moved to other dates if they ocur with some other celebrations;
   - they should be sorted by date from 1 Jan to 31 Dec;
- movable celebrations:
   - celebrations that are directly dependent on other celebrations (date of celebration defined like `Thursday after Pentecost`) or have a specially calculated date (like Easter);
   - they should be sorted by date from First Sunday of Advent to Saturday after the last (usually 34th) Sunday of the Ordinary Time.

**Comment by tukusejssirs** [comment]
By using the above-mentioned parameter using the ranks from the GILH, we should drop the following ‘titles’ from `src/constants/titles.constant.ts`:

- `FEAST_OF_THE_LORD`;
- `MARIAN_FEAST`;
- `TRIDUUM`.

These are not titles.

**Comment by tukusejssirs** [comment]
Also note that although some of the celebrations defined in `Celebrations.ts`, are also defined in `general.ts`.

For example `exaltationOfTheHolyCross`:

```js
// Dates.js
const exaltationOfTheHolyCross = (year: number): dayjs.Dayjs => dayjs.utc(`${year}-9-14`);

// Celebrations.js
{
  key: 'exaltationOfTheHolyCross',
  rank: RanksEnum.FEAST,
  date: Dates.exaltationOfTheHolyCross(year),
  liturgicalColors: LiturgicalColorsEnum.RED,
  metadata: {
    titles: [TITLES.FEAST_OF_THE_LORD],
  },
  prioritized: true,
},

// general.ts
{
  key: 'exaltationOfTheHolyCross',
  source: 'celebrations', // Override the default lookup source
  rank: RanksEnum.FEAST,
  date: dayjs.utc(`${year}-9-14`),
  liturgicalColors: LiturgicalColorsEnum.RED,
},
```

**Comment by emagnier** [comment]
In fact it's more about a triage between liturgical days from the proper of seasons, and days from the sanctorale.

**Comment by tukusejssirs** [comment]
That might be the case, however, I still think that _all_ celebrations should be defined in a _calendar_ (i.e. in `general.ts` if it is celebrated in the GRC). That makes it easier to proof or make changes as the Holy See might change a bit here and there.

**Comment by emagnier** [comment]
Since the refactor I made internally on the calendar builder, I have to double check but I think it's no more necessary to have them separated into these 2 existing files.
So as I just proposed, we could have them separated into 2 files, the sanctorale (ordered by date), and the proper of seasons. Or gather everything into one file (the file might be a bit longer).

**Comment by tukusejssirs** [comment]
I think that all celebrations defined in `Celebrations.ts` should be moved into `general.ts`, no matter if the celebration is from sanctoral or the proper of seasons. From my point of view, `general.ts` should contain all celebrations celebrated according to the GRC, while other (particular) calendars should contain all the _changes_ to `general.ts` (and to other calendars based on calendar inheritance; see #48). I don’t think that the length of the `general.ts` file matter; it should be as long as needed. The (longer) functions (like the Easter Calculus) might be better to be included in the `src/lib/utils/dates.ts` (as I have already proposed), while the shorter ones (one or two lines in length) should be within the calendar definitions in `general.ts`.

> […] I have to double check […]

I don’t want to nitpick, but please see [this comment of mine](https://github.com/romcal/romcal/issues/210#issuecomment-676293692) if the celebration definition in `Celebrations.ts` (and `Dates.ts`) is not a duplicate definition of the very same celebration. I am not sure, but it looks like it.

**Comment by emagnier** [comment]
I agree with you, I was just adding the technical point of view to say that everything is now possible (although I've to double-check in the codebase since I still see some "old" code that might need to be removed). 

And `easter` is already computed in `/dates.ts`. This file doesn't contain calendar definitions, it's just a library that contains rules to calculate dates correctly (within a provided year) for the most important liturgical days.

Concerning liturgical days that are defined both in `general.ts` and `celebrations.ts`, only one will be taken (and the other one dropped) by romcal, depending on its rank and if it has the `prioritized` option. If they have the same rank or have both the prioritized option, the one in `general` will be taken, and the other one in `celebrations` will be dropped. Indeed we should do some cleanup here to remove duplicates.

**Comment by tukusejssirs** [comment]
> And `easter` is already computed in `/dates.ts`.

Indeed, it is calculated in `src/lib/Dates.ts`, however, I propose to remove that file altogether and EITHER move all the celebration date definition (along with the celebration definitions from `Celebrations.ts` to `general.ts` OR move _most_ of the functions (the shorter functions, which are approx one or two lines in length) to `general.ts` and the lengthy functions (like the Easter Calculus) somewhere under `src/utils` (e.g. `src/utils/dates.ts`).

> This file doesn't contain calendar definitions it's just a library that contains rules to calculate dates correctly (within a provided year) for the most important liturgical days.

Yes, but some of the definitions (e.g. `const divineMercySunday = (year: number): dayjs.Dayjs => easterSunday(year).add(7, 'day').startOf('day');` or `const nativityOfJohnTheBaptist = (year: number): dayjs.Dayjs => dayjs.utc(`${year}-6-24`);`) are so simple that those should definitively be moved from there into the celebration definition of that particular celebration (like we do for the most celebrations in `src/calendars/*`).

> Concerning liturgical days that are defined both in `general.ts` and `celebrations.ts`, only one will be taken (and the other one dropped) by romcal, depending on its rank and if it has the `prioritized` option. If they have the same rank or have both the prioritized option, the one in `general` will be taken, and the other one in `celebrations` will be dropped. Indeed we should do some cleanup here to remove duplicates.

I am not talking about the celebration prioritisation now, but about the _duplicate_ definition (i.e. worthless, wasteful and unnecessary definition) of a particular celebration (`exaltationOfTheHolyCross`). Nevertheless, I see you got that part. :smiley:

**Comment by emagnier** [comment]
As I already said, `dates.ts` and `general.ts` + `celebrations.ts` do not serve the same thing. `Dates.ts` is a very important library that allows then (on a second phase during the calendar calculation) to compute `general.ts`, `celebrations.ts`, and all other calendars. If you want to change that, it will be the right way to make the codebase messy and break the things 😉 . Please leave the codebase architecture to the developers 😄 

> I am not talking about the celebration prioritisation now

You asked questions and I was just giving you the explanation on how things work to do the cleanup (rank and prioritized options must be understood to know which calendar definition could be removed).

**Comment by tukusejssirs** [comment]
> Please leave the codebase architecture to the developers smile

Okay. I’ve just taken deeper look where is `src/lib/Dates.ts` used/imported and it really looks like those celebration dates definitions (even those simple, one or two line in length) should be kept in there, because otherwise those dates won’t be accessible from all the scripts/programs. Sorry I bothered you with my nonsense. :disappointed:

> You asked questions and I was just giving you the explanation on how things work to do the cleanup (rank and prioritized options must be understood to know which calendar definition could be removed).

Okay, thanks! However, I wasn’t suggesting that _I_ should be the one to choose which one should be removed. I wanted (and still want) to leave it up to you. :smiley:

---

Hopefully, we both agree that the celebration definitions from `Celebrations.ts` should be moved to `general.ts`, while the celebration dates definition would be kept in `src/lib/Dates.ts`. :smiley:

**Comment by emagnier** [comment]
No worries. In fact all the methods in the `Dates` class are already available externally. They output a `Date` only, not a liturgical day object (with all its properties). It's not documented yet because I need to review some technical points first.

**Comment by tukusejssirs** [comment]
@emagnier, is moving of the celebration definitions from `celebrations.ts` into `general.ts` (in the TS branch) as simple as copying (moving) the celebration definitions from `celebrations.ts` into `general.ts`, or does it require something more to do?

**Comment by emagnier** [comment]
Yes. But you will have to also move the corresponding localised keys in the localisations files, from the `celebrations` part to `sanctoral` part. Also the `sanctoral` name might not anymore appropriate here, in this case we could simply use `celebrations` as it's a more general term.

**Comment by tukusejssirs** [comment]
I see. Anyway, this is what I wanted to hear (I was afraid there were some ‘hidden’ attachments to `celebrations.ts` somewhere else in the code).

As for the `sanctoral`/`celebrations` sections in the l10n files, I think that the distinction between celebration (or as I call it an _event celebration_) and personal celebrations (which are part of the sanctoral) is not yet clearly distinguished in the l10n files (see #108). Therefore I don’t a reason why should we not merge them for now.

However, I think that we should (later on) distinguish between the two types of celebration, because we’d like to implement #208 (aka Martyrology) and we also want to separate metadata from the celebration names (in l10n files; see #154) and therefore the two types of celebration will need different approach

I also think that `celebrations` object name is quite misleading as all events and personal celebrations are celebrations _per se_. I suggest to change it either to `events` or `evental` (thought it is not a real word) or anything else that would better fit and distinguish these celebrations from the sanctoral.

---

 Back to the topic: what do you think? Can I move the celebration definitions from `celebrations.ts` to `general.ts`, while merging `celebrations` into `santoral` in l10n keys? Should I do it as part of PR #213 (which might not be quite good idea, as that PR is quite big already) or should I wait until it is merged?

**Comment by tukusejssirs** [comment]
I think that what we currently call `source` (see #247), i.e. `celebrations` could be used the differentiate between `temporale`, `sanctorale` and `evantale`/`events` (or whatever name fits better). I think that it should not assumed and therefore it should be always configured in all celebration definitions.

**Comment by emagnier** [comment]
I think this issue is not valid anymore, because it was relying on romcal v1 and v2 (and deprecated metadata like `source`). In `v3` the management of these `LiturgicalDay` object has been drastically refactored.

Since `v3`, all the base`LiturgicalDay` object are defined in the `general-calendar/proper-of-time.ts` (this calendar make sure that every day of the year have at least one `LiturgicalDay`), and all others items from the GRC are defined in the `general-calendar/proper-of-saints.ts`. Each `LiturgicalDay` object also have a `fromCalendar` that contain the name of the calendar where it has been defined.

**Comment by tukusejssirs** [comment]
You’re right, @emagnier, I’ll close this issue, as it was resolved, albeit differently than proposed (it is much better now I think). :+1:
