### ISSUE TITLE
Utility of the `.queryFor` method

### ISSUE THREAD

**Issue by emagnier** [pejulian/romcal#215]
The `.queryFor` method is only available for users (not being used internally), to filter the romcal results, and/or group the results per predefined segments.

But...

- The proposed filters options are very limited, while this is something very easy to do with native JavaScript on all romcal metadata.

- Grouping results is also something easy to do with the native JavaScript `reduce` method, and this is available on Node.js and all modern browsers (except IE, but easy to polyfill or replace by Lodash).

I propose to:

- [x] Remove the filtering options: doing it with native JavaScript is much cleaner and you can do a lot more.
- [x] Keep only the group feature, and wraps it in a new `groupBy` method. The current proposed groups are very subjective and of course incomplete (who is using this feature?), but we could reassess the need to keep it or not later.
- [x] Remove the `.queryFor` method and related options.
- [x] In documentation: add one or two examples of filtering romcal results. Idem for grouping results (using native JavaScript).

**Comment by tukusejssirs** [comment]
Well, I somewhat agree with you.

Just to be clear: you propose to remove all query functionalities from romcal? Thus the users will be able to search a celebration by parsing the output JSON, right? Won’t it be better (from performance point of view) to let the user to search, for example, for a celebration date (and other metadata) of the celebration named `St Francis of Assisi` in the specified year (if not celebrated in that particular year and/or in that particular calendar, the output JSON should be either empty or it should contain a single value in the sense of `No such celebration is celebrated in {calendar} in {year}.`. What do you think?

**Comment by emagnier** [comment]
The query functionalities in romcal are just a layer on top of romcal. And yes, I propose to remove it, since this feature is actually very limited, and is a duplicate of what JavaScript already provide (in a much better way) to natively filter, find, sort... everything from romcal.

And I'm tempted to remove the grouping functionalities as well, because the proposed choices are still very subjective and will never cover everything. Instead we could provide examples on how to do it natively.

**Comment by tukusejssirs** [comment]
Well, if you don’t want to improve the querying (for performance reasons), then from my point of view it should be removed. However, I think it might be a good idea to implement a way to get the celebration(s) for a particular day (like `today`), that might be useful for websites.

As for the grouping, don’t you think that they should be rather _improved_ than _removed_?

**Comment by emagnier** [comment]
> Well, if you don’t want to improve the querying (for performance reasons)

I'm repeating myself, but it's especially because it's impossible to cover everything when you can already do everything natively in javascript in a much better way.

But indeed the only things that could be improved is everything about dates. Manipulating and reading dates natively in JS is not always user-friendly. I thought to make a proposal soon, but let's do it here (because it's related).

Romcal output an array of celebrations, that could be filtered as such: 
- `.before(date)`
- `.sameOrBefore(date)`
- `.yesterday()`
- `.today()`
- `.tommorow()`
- `.sameOrAfter(date)`
- `.after(date)`

The `date` parameter could be a native `Date` object, or a string containing the key of a celebration.

For example
```js
var calendar1 = Romcal.calendarFor({ year: 2021, locale: 'fr' }).sameOrAfter(new Date(2020, 8, 22))
var calendar2 = Romcal.calendarFor({ year: 2021, locale: 'fr' }).before('assumption')
var today = Romcal.calendarFor({ year: 2021, locale: 'sk' }).today()
```

> As for the grouping, don’t you think that they should be rather improved than removed?

I already answered and gave the reasons. And as I proposed in my first comment, the existing grouping features will be wrapped in a new `.groupBy` method (as long as we support IE11). But we should consider to completely remove it later. Because it's definitely not the romcal job to do this kind of user-specific needs when there are already native features or libraries such as Lodash and Dayjs that will do the job much better, while giving a lot more possibilities to the user.

**Comment by tukusejssirs** [comment]
Okay, @emagnier, now I understand your approach and proposal(s) better. I absolutely agree with you.

**Comment by sdegutis** [comment]
So, is there currently any native way to get the feast for the current day? Or do I just have to build up a query based on a new Date object, to filter to today, and get the 0 index object?

**Comment by sdegutis** [comment]
This is what I came up with: `Romcal.calendarFor({query: { month: new Date().getMonth() }})[new Date().getDate()-1]`

**Comment by sdegutis** [comment]
Found out how to get today's feasts:

```js
Romcal.calendarFor({country:'unitedStates'},true).filter(date => date.moment.isSame(new Date(), 'day'))
```

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
