### ISSUE TITLE
Liturgical year should be the second year (the almost whole part of the civil year)

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#216]
Related: [this discussion](https://github.com/romcal/romcal/commit/c530bd704113793ec5ca2785dd6fd502cc1b463e#r41491701).

---

Liturgical year is usually called either as `year/year++` (e.g. `2020/2021`) or simply `year` (e.g. `2021`).

Currently, however, we use the former year (`2020`), which only contains approximately a month of a civil year, which I think can be considered incorrect. It should use the second year, the year that contains most of the civil year (approx 11 months).

**Comment by emagnier** [comment]
Addressed on https://github.com/romcal/romcal/pull/250.
