### ISSUE TITLE
Corpus Christi on Sunday and `general.ts`

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#217]
I don’t think that in the GRC Corpus Christi is celebrated on Sunday, however, in `general.ts` we have `corpusChristiOnSunday` set to `true`.

**Comment by emagnier** [comment]
I'm not sure to understand this issue.

Should `corpusChristiOnSunday` be set to `true` or `false` by default in the GRC?

**Comment by tukusejssirs** [comment]
As far as I know, yes. As far as I know, in the GRC, the Epiphany of the Lord, Corpus Christi and Ascension are all celebrated on their proper days and are not transfered to the following Sunday.

**Comment by emagnier** [comment]
So all of these properties should be set to `false` by default, from the GRC:

https://github.com/romcal/romcal/blob/a82c81d05b658f037f9035011cb6dd9793d65f60/lib/general-calendar/proper-of-saints.ts#L13-L17

---

Additional note to myself:

> The `ParticularConfig` in`proper-of-saints.ts` should be removed, because it is redundant from:
>
> https://github.com/romcal/romcal/blob/a82c81d05b658f037f9035011cb6dd9793d65f60/lib/models/config.ts#L62-L67
>
> And this could also create misunderstanding, if we only retrieve data from the proper of time.

**Comment by tukusejssirs** [comment]
> So all of these properties should be set to `false` by default, from the GRC:
> 
> https://github.com/romcal/romcal/blob/a82c81d05b658f037f9035011cb6dd9793d65f60/lib/general-calendar/proper-of-saints.ts#L13-L17

Fixing this part is easy. I could fix it after we merge #350, unless you want to do some additional changes.

> Additional note to myself:
> 
> > The `ParticularConfig` in`proper-of-saints.ts` should be removed, because it is redundant from:
> > https://github.com/romcal/romcal/blob/a82c81d05b658f037f9035011cb6dd9793d65f60/lib/models/config.ts#L62-L67
> > 
> > And this could also create misunderstanding, if we only retrieve data from the proper of time.

Although it is a note to yourself, you seem to want to change some details I am not yet familar with (in regards to romcal’s source code). If that is the case, could you find some to deal with this issue? It seems like a quick and easy issue. :wink:

**Comment by emagnier** [comment]
I don't remember what I meant here for the note to myself. It's been several months since I've worked in the codebase, so I'll have to make time for that.

But in the meantime, if you have time to adjust these 3 options (set `false` by default in the GRC, and adjust particular calendars), indeed, do not hesitate to do it. Thanks 🙏
