### ISSUE TITLE
Licence prepended to some files

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#218]
Some files contain the romcal licence (MIT), most of them not. I think we might want to unify this.

Generally, there two options:
1. prepend the licence to all files;
2. remove the licence from all files and keep the licence in the `LICENSE` file only.

I am for the second options as it reduces the codebase size.

---

Licence subissues:

1. I think that the `LICENSE` file should be renamed to `LICENSE.txt` file to explicitly denote the file type.

2. The year in the `LICENCE` file (and all files that contain the licence): currently, it is `2018` (in `src/lib/Dates.test.ts`, we have `2014`).

3. The copyright owner: currently, we list only @pejulian (`Julian Pereira`), which I am okay with, however, in `src/lib/Dates.test.ts`, we have `Pereira, Julian Matthew`.

**Comment by emagnier** [comment]
+1 to remove the licence from all files and keep the licence in the `LICENSE` file only.

Not ok to rename it to `LICENSE.txt`, because `LICENSE` is a widely used naming convention.

And this isn't a bug.

**Comment by tukusejssirs** [comment]
> Not ok to rename it to `LICENSE.txt`, because `LICENSE` is **a widely used naming convention**. [emphasis mine]

This isn’t a reason _per se_, because the _convension_ is to name it either `licence` or `licence`, while the casing nor extension does not matter. It can be even `LICENSE.md` if you wish. Even GitHub looks for any filename starting with one of the [pre-defined patterns](https://github.com/davglass/license-checker/blob/de6e9a42513aa38a58efc6b202ee5281ed61f486/lib/license-files.js#L3-L10).

However, we can keep the filename if you wish.

**Comment by emagnier** [comment]
Since romcal `v3`, the license is now only:
- in the LICENSE file (in the codebase).
- prepended on top of the built files (built romcal core library and all its calendar plugins).

**Comment by tukusejssirs** [comment]
>     * prepended on top of the built files (built romcal core library and all its calendar plugins).

Yes, the issue fixed, but you forgot to update the year and authors (I think you should include at least your name) in the built files. It still says `Copyright (c) 2018 Julian Pereira`. I think the year could be a variable, either current year at build time or (maybe better) current year at release time (it could be changed by GitHub Actions in the release section).
