### ISSUE TITLE
add `enGb` and `enUs` locales

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#22]
I think it would be nice to separate the `enGb` and `enUs` locales, as these two main/general Englishes / English accents have some differences. You can either go the way of total separation (each `en**` would contain every string/key), but it would require doubling some/many keys.

Probably better way would be to use `enUs.mjs` locale (chosen because you are American, don’t you? otherwise I would suggest `enGb.mjs`, for I prefer British English to American one ;)) as a ‘meta-locale’ (or however you would call it), which would contain default value for all Englishes (gb, us, ca, nz, etc). It would behave as `general.mjs` calendar for calendars, only for Englishes. Then, every key in `en[^U][^s].mjs` different from `enUs.mjs` would be re-set in `en[^U][^s]`.

The same thing could be done for other languages (e.g. Spanish, Portugese), which are used in different countries.

Here are list of countries, which use English:

| Country | [IETF language tag](https://en.wikipedia.org/wiki/Language_code#Common_schemes) / code |
|---------|-----------|
| Australia - English | en-AU |
| Belize - English | en-BZ |
| Canada - English | en-CA |
| Caribbean - English | en-CB |
| India - English | en-IN |
| Ireland - English | en-IE |
| Jamaica - English | en-JM |
| Malaysia - English | en-MY |
| New Zealand - English | en-NZ |
| Republic of the Philippines - English | en-PH |
| Singapore - English | en-SG |
| South Africa - English | en-ZA |
| Trinidad and Tobago - English | en-TT |
| United Kingdom - English | en-GB |
| United States - English | en-US |
| Zimbabwe - English | en-ZW |

**Comment by pejulian** [comment]
Hi @tukusejssirs 

Actually, I am from Malaysia :)

The current mechanism of `romcal` is to default to the `en` locale which is actually `en-US`.
I should probably rename this file to make it clearer that `en-US` is the default locale being used.
This is what I will do to resolve this issue for now.

At present, I have not defined the other English locale files as I haven't got meaningful translations for them yet. If I made them, they would just contain duplicates of `en.mjs` which doesn't really bring much value to the end user. For now, if one of the above locales is defined (i.e. `en-MY`), only `momentjs` will use it to apply relevant time formatting to the calendar date output.

I do hope however, that this module may reach a wider user audience in the future and that more translation files can be contributed.

**Comment by pejulian** [comment]
I have checked in a fix where the default locale file is now named `enUs.mjs` to avoid confusion as to which locale is being used.
