### ISSUE TITLE
Calendar config: add a option to set/override the calendar inheritance

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#249]
I think we should add another calendar configurition option which should either set the calendar inheritance or override the default calendar inherintace.

This would help for example with #222: when we implement #48 (calendar inheritance), we should create a `russia.ts` calendar with all celebrations celebrated countrywide, however it should inherit from `general.ts` only (not from `europe.ts` nor `asia.ts`). Then we should create a calendar for European Russia and another one for Asian Russia, both of which would inherit from `general.ts` and their continent and they might define some additional celebrations.

**Comment by emagnier** [comment]
This question have been already discussed here: https://github.com/romcal/romcal/issues/48#issuecomment-565650048, and there is already a proposal. No need to create another issue here.

**Comment by tukusejssirs** [comment]
Oh, sorry then. I thought it dealt with the inheritance only, not the confiuration. My bad. :disappointed:
