### ISSUE TITLE
Vietnamese localization

### ISSUE THREAD

**Issue by tommai4881** [pejulian/romcal#255]

**Comment by emagnier** [comment]
Hello @tommai4881, welcome on the romcal project!

Can you elaborate a little more? Do you wish to have the Vietnamese localisation? Or do you plan to contribute to make it happen? Depending of your time and what you can do, there is multiple way to contribute. Let us know if you need help!

**Comment by tukusejssirs** [comment]
@emagnier was faster than me to comment on this issue. :wink:

I’d like to add that AFAIK there is no current or past romcal contributor who speaks Vietnamese. If you find some time to contribute to romcal, even the [Vietnamese calendar](https://github.com/romcal/romcal/blob/_F-TypeScript/src/calendars/vietnam.ts) would use some tending. You could also use the celebrations list from [Wikipedia](https://en.m.wikipedia.org/wiki/General_Roman_Calendar#Vietnam), although it might a better idea to double-check it from the Vietnamese Roman Missal.

Nevertheless, any kind of contribution is most welcome! :smiley:

**Comment by emagnier** [comment]
I'm closing this issue since there is no relevant discussion.

Note: it might be related to the contribution to this PR https://github.com/romcal/romcal/pull/276.
