### ISSUE TITLE
Localise St Faustina Kowalska into French

### ISSUE THREAD

**Issue by scriptura** [pejulian/romcal#258]
Salutation ;)

EN : In your translation files you are missing Saint Faustina Kowalska. Since May 18, 2020, the celebration of Saint Faustina now has the rank of optional memory.

FR : Dans vos fichiers de traduction il vous manque Sainte Faustine Kowalska. Depuis le 18 mai 2020 la célébration de sainte Faustine a désormais rang de mémoire facultative.

http://www.vatican.va/roman_curia/congregations/ccdds/documents/rc_con_ccdds_doc_20200518_decreto-celebrazione-santafaustina_en.html

**Comment by tukusejssirs** [comment]
Actually, it is not missing from the [General Roman Calendar](https://github.com/romcal/romcal/blob/_F-TypeScript/src/calendars/general.ts#L1057:L1062) (in the romcal codebase), but only from `fr.ts`.

If you want, you can add it into `fr.ts` using `faustina_kowalska_virgin` key name. And if you have even more time, you can localise even other keys not yet localised into French. Just look at [`en.ts`](https://github.com/romcal/romcal/blob/_F-TypeScript/src/locales/en.ts).

**Comment by tukusejssirs** [comment]
This issue was fixed in 86714dae5, closing.
