### ISSUE TITLE
Add a romcal option to generate a proper for the selected calendar

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#262]
Related #234

---

I think we should have an option to generated a proper for any supported calendar, be it the GRC or any particular calendar.

There should be a suboption to output the ferias/weekdays in the output, that is:
- when this suboption is turned on:
   - romcal would output each day in a year (even 29 Feb);
   - this output could be used to generate the calendar printed at the beginning of the Roman Missal or the Liturgy of the Hours;
- when it is turned off:
   - romcal would output only those days that do have a celebration of an event or a saint/blessed;
   - this could be used to generate the ‘simple’ proper that is usually printed in _Ordos_.

Another suboption that would be nice to have, is if romcal should output the celebrations defined in the GRC or not. In the propers usually printed in the _Ordos_, these celebrations are omitted. Anyway, this does not need to be implemented as a romcal option, it could be a celebration property in the output object.

**Comment by tukusejssirs** [comment]
Note that this is related to #234, which could use implementation of this issue to add the commit hook.

**Comment by emagnier** [comment]
FYI this feature is now part of romcal `v3`.

https://github.com/romcal/romcal#get-all-liturgical-day-definitions-getalldefinitions
