### ISSUE TITLE
Improvements in the Czech locale

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#267]
@igneus, after some time, I’ve found some time to create an issue as [you requested](https://github.com/romcal/romcal/pull/248#issuecomment-740233319). Of course, you are not required to answer my questions or improve romcal anyway.

I will maintain list of (potential) issues or some uncertainties in the description of this issue. Feel free to answer or discuss some/all of them in this issue.

---

Issues/questions/whatever:

- [ ] In Czech Republic, are Epiphany, Ascension, and Corpus Christi celebrated on their original day or are they transfer to the following Sunday?
- [ ] Proof the _national_ proper below please. Note that by _national_ proper I mean a proper valid countrywide, without any added celebrations celebration in a particular diocese or city, or just Bohemia or just Moravia.

   <details>
     <summary>Czech National Proper</summary>

   | Date   | Celebration | Rank | Change against the GRC | Questions |
   |--------|-------------|------|------------------------|-----------|
   | 18 Jan | Panny Marie, Matky jednoty křesťanů | memorial | addition |  |
   | 10 Mar | Sv. Jana Ogilvie, kněze a mučedníka | optional memorial | addition |  |
   | 23 Apr | Sv. Vojtěcha, biskupa a mučedníka, hlavního patrona pražské arcidiecéze | feast | rank raise | Is he celebrated in the Archdiocese of Prague only? If yes, is it just a mere optional memorial in other dioceses? |
   | 24 Apr | Sv. Jiří, mučedníka | optional memorial | transfer from 23 Apr |  |
   | 29 Apr | Sv. Kateřiny Sienské, panny a učitelky církve, patronky Evropy | feast | rank raise and patronage title addition |  |
   | 30 Apr | Sv. Zikmunda, mučedníka | optional memorial | addition |  |
   | 6 May  | Sv. Jana Sarkandra, kněze a mučedníka | optional memorial | addition |  |
   | 8 May  | Panny Marie, Prostřednice všech milostí | optional memorial | addition |  |
   | 16 May | Sv. Jana Nepomuckého, kněze a mučedníka, hlavního patrona Čech | feast | addition | Is he celebrated in the Czechia/Bohemia only (and not in Moravia)? If yes, is it just a mere optional memorial elsewhere? |
   | 20 May | Sv. Klementa Marie Hofbauera, kněze | optional memorial | addition |  |
   | 30 May | Sv. Zdislavy | optional memorial | addition | As far as I understand it well, in the national Proper, it is a mere optional memorial. |
   | Thu after Pentecost | Ježíše Krista, nejvyššího a věčného kněze | feast | addition |  |
   | 15 Jun | Sv. Víta, mučedníka | optional memorial | addition |  |
   | 19 Jun | Sv. Jana Nepomuckého Neumanna, biskupa | optional memorial | addition |  |
   | 4 Jul  | Sv. Prokopa, opata | optional memorial | addition |  |
   | 5 Jul  | Sv. Cyrila, mnicha, a Metoděje, biskupa, patronů Evropy | feast | rank raised and date moved | As I understand it, the celebration is a solemnity in Moravia only, am I right? |
   | 11 Jul | Sv. Benedikta, opata, patrona Evropy | feast | rank raise and patronage title addition |  |
   | 14 Jul | Bl. Hroznaty, mučedníka | optional memorial | addition |  |
   | 17 Jul | Bl. Česlava a sv. Hyacinta, kněží | optional memorial | addition |  |
   | 23 Jul | Sv. Brigity, řeholnice, patronky Evropy | feast | rank raise and patronage title addition |  |
   | 27 Jul | Sv. Gorazda a druhů | optional memorial | addition |  |
   | 9 Aug  | Sv. Terezie Benedikty od Kříže, panny a mučednice, patronky Evropy | feast | rank raise and patronage title addition |  |
   | 25 Aug | Sv. Benedikta, Jana, Matouše, Izáka a Kristina, mučedníků | optional memorial | addition |  |
   | 7 Sep  | Sv. Melichara Grodeckého, kněze a mučedníka | optional memorial | addition |  |
   | 10 Sep | Bl. Karla Spinoly, kněze a mučedníka | optional memorial | addition |  |
   | 16 Sep | Sv. Ludmily, mučednice | optional memorial | addition |  |
   | 17 Sep | Sv. Kornélia, papeže, a Cypriána, biskupa, mučedníků | optional memorial | rank lowered and date moved |  |
   | 28 Sep | Sv. Václava, mučedníka, hlavního patrona českého národa | solemnity | rank raised and patronage title addition |  |
   | n/a    | Sv. Vavřince Ruize a druhů, mučedníků | n/a | dropped |  |
   | 12 Oct | Sv. Radima, biskupa | optional memorial | addition |  |
   | 21 Oct | Bl. Karla Rakouského | optional memorial | addition |  |
   | 31 Oct | Sv. Wolfganga, biskupa | optional memorial | addition |  |
   | 25 Oct or the following Sun | Výročí posvěcení vlastního kostela | solemnity | addition | (only in consecrated churches whose date of consecration is unknown) |
   | 13 Nov | Sv. Anežky České, panny | memorial | addition |  |
   | 1 Dec  | Sv. Edmunda Kampiána, kněze a mučedníka | optional memorial | addition |  |
   </details>

- [ ] What is the rank of All Souls?
   - in [`czech-cs.txt`](https://github.com/igneus/calendarium-romanum/blob/master/data/czech-cs.txt#L226), @igneus list it as solemnity (`s`);
   - [Wiki (en)](https://en.wikipedia.org/wiki/General_Roman_Calendar#November), they say it is `ranked with solemnities`;
   - in the Slovak _Ordos_, we don’t list any rank with the celebration.

- [ ] Is St Adalbert celebrated as `[principal] patron of the Archdiocese of Prague` in whole Czech Republic (as it is listed in [`czech-cs.txt` (L62)](https://github.com/igneus/calendarium-romanum/blob/4918754ca64d501e3c62165d1512adbbabcc9148/data/czech-cs.txt#L62)) or is it celebrated as a memorial (as it commented above in the romcal codebase) or is it celebrated as a mere optional memorial (inherited from the GRC)?
- [ ] What should be the title of `cyril_the_philosopher_monk_and_methodius_of_thessaloniki_bishop_copatrons_of_europe`: `Copatrons of Europe` or `Copatrons of Europe and Patrons of Moravia` (as it is listed in [`czech-cs.txt`](https://github.com/igneus/calendarium-romanum/blob/4918754ca64d501e3c62165d1512adbbabcc9148/data/czech-cs.txt#L122)). Note that we we need the celebration metadata as it is celebrated in the particular calendar for Czech Republic, not for Dioceses nor Bohemia nor Moravia.
- [ ] How should be `Josemaría Escrivá de Balaguer` inflected? (see [this comment](https://github.com/romcal/romcal/pull/248#discussion_r516887877))
- [ ] How should be `Jan Maria Grignion` inflected? (see [this comment](https://github.com/romcal/romcal/pull/248#discussion_r516877800))
- [ ] What are holy days of obligation in Czech Republic?
- [ ] Why do you in Czech call Blessed Isabelle of France _Alžbeta_ (Elizabeth; [src](https://cs.wikipedia.org/wiki/Al%C5%BEb%C4%9Bta_Francouzsk%C3%A1))?

**Comment by TobiTenno** [comment]
given that we already have #125, could this be merged into it, given these are both part of creating the czech locale, and that the former issue is for creating the locale? either way, it's redundant, and one of them should be closed

**Comment by tukusejssirs** [comment]
True, they should be merged. If you want you can do it. If not, I can do it, but the PRs are of greater priority to me right now.

**Comment by TobiTenno** [comment]
merging w/ #125
