### ISSUE TITLE
Add tests for the calendar metadata

### ISSUE THREAD

**Issue by emagnier** [pejulian/romcal#288]
On each **liturgical day objects**, romcal now output a few contextual information about the day within the `calendar`: https://github.com/romcal/romcal/blob/dev/docs/data-output.md#json-structure. 

```
  // ...
  calendar: {
    totalWeeksInGregorianYear: 53,
    totalWeeksInLiturgicalYear: 52,
    weekOfGregorianYear: 1,
    weekOfLiturgicalYear: 5,
    weekOfSeason: 2,
    dayOfGregorianYear: 1,
    dayOfLiturgicalYear: 32,
    dayOfSeason: 8,
    dayOfWeek: 3,
    dayOfWeekCountInMonth: 1,
    startOfLiturgicalYear: '2019-12-01T00:00:00.000Z',
    endOfLiturgicalYear: '2020-11-28T00:00:00.000Z',
    easter: '2020-04-12T00:00:00.000Z',
  },
  // ...
```

However, there is actually no written tests about these new data, and I think it deserves it.

**Comment by tukusejssirs** [comment]
I am for implementing of this.

> `dayOfWeekCountInMonth`

What this the property about? What do you mean by `week count`? I think the key name needs a change to be more understandable.

> `startOfLiturgicalYear` and `endOfLiturgicalYear`

And what about start and end of the liturgical seasons?

> However, there is actually no written tests about these new data, and I think it deserves it.

I also think that the tests should written for this, ideally before the `v2.0.0` release, however, it might not be a release blocker.

**Comment by emagnier** [comment]
It already exists in romcal. 

This ticket within the v2 milestone was opened to not forgot to add the missing tests before the release.

---

> dayOfWeekCountInMonth

`dayOfWeek` generally represent the day name: Monday, Tuesday...
So here it counts the `dayOfWeek` position within a month.
E.g. the first Monday of the month, the third Friday of the month...

The documentation on that part is a bit poor (whether in the `.md` files or codebase).
Indeed, it could be improved, so modern IDEs will provide a text hint when using or seeing this property.

If you have a better idea to name this property (not too long), I'm also open for that. But maybe documenting this property is enough.

---

> `startOfLiturgicalYear` and `endOfLiturgicalYear`: And what about start and end of the liturgical seasons?

Why not. I'm open for contributions for that (in future releases). I will not add new features here.

**Comment by tukusejssirs** [comment]
Agreed on / understand all points. :wink:

> If you have a better idea to name this property (not too long), I'm also open for that. But maybe documenting this property is enough.

Well, the `Count` substring is a bit ambiguous IMO, as _count_ means a number of something and is represented by a [_cardinal number_](https://en.wikipedia.org/wiki/Cardinal_number). I’d rather omit it, but that is probably still not ideal, as it does not say anything that the property contains the _ordinal position_ of a week day in a particular month. How could be name the property to tell the users what it actually represents? `dayOfWeekNumberInMonth`? Or `dayOfWeekPositionInMonth`?

> Why not. I'm open for contributions for that (in future releases). I will not add new features here.

Agreed. Therefore we should create a separate issue for that in order to not forget about it. :wink:

**Comment by emagnier** [comment]
> as count means a number of something and is represented by a cardinal number.

Actually, this property will return a number between 1 and 5. The `Number` keyword is too vague IMO. I like the `Position` keyword since it also refer to an index position within a scope. Maybe `dayOfWeekIndexInMonth` could be another alternative (but `index` generally starts from `0`, that could create confusion).

So we go for `dayOfWeekPositionInMonth`?

> Agreed. Therefore we should create a separate issue for that in order to not forget about it. 😉

Please. 😉

**Comment by tukusejssirs** [comment]
> The `Number` keyword is too vague IMO.

From your point of view yes, as you probably look at the word _number_ and a data type, but as a word in the context of _day of week number_ it is the correct one (as opposed to _count_). Just think of it as in _number of words_. :wink:

> I like the `Position` keyword since it also refer to an index position within a scope. Maybe `dayOfWeekIndexInMonth` could be another alternative (but `index` generally starts from `0`, that could create confusion).
>
> So we go for `dayOfWeekPositionInMonth`?

Okay, go for it. Still I don’t think it is the best possible way to describe it, but I can’t think of a better description right now. :shrug:

**Comment by emagnier** [comment]
Ok, I will wait a bit before going forward on it, just to think more about it.

Between:
- dayOfWeekNumberInMonth
- dayOfWeekPositionInMonth

**Comment by emagnier** [comment]
Just a note, in romcal `v3` I've adopted `nthDayOfWeekInMonth` instead of dayOfWeekNumberInMonth or dayOfWeekPositionInMonth.

**Comment by tukusejssirs** [comment]
I agree that `nthDayOfWeekInMonth` is good choice.
