### ISSUE TITLE
Enquiry - not issue: What happened to the branch _typescript?

### ISSUE THREAD

**Issue by pvanthony** [pejulian/romcal#291]
I am not a programmer. Please bear with me.
If I remember correctly there was a branch named something like _typescript.
Has this been merged with dev branch?

I ask because I using that branch to try some code.

**Comment by tukusejssirs** [comment]
Yes, it was merged in #250 into the `dev` branch, which became the default branch. The `_F-TypeScript` was just a long-lived feature 
branch.

**Comment by pvanthony** [comment]
Great. Thank you for the reply.
