### ISSUE TITLE
Not an issue. Need advice. Script takes time to load.

### ISSUE THREAD

**Issue by pvanthony** [pejulian/romcal#293]
Currently using the javascript in the browser like the following.
`<script type="text/javascript" src="node_modules/romcal/dist/es5/romcal.bundle.min.js"></script>
`
Seems like the web pages take time to download the script. Is there a way to do the processing on the server and return just today's data? Then the page might load faster, I think.

Is using romcal-api the only way to achieve this?

**Comment by tukusejssirs** [comment]
> Is there a way to do the processing on the server and return just today's data?

If you want to do the processing on the server, you need to use _server-side Javascript_, i.e. [Node.js](https://nodejs.org/en/). For that you need access to the server (VPS), e.g. via SSH; this cannot be done if you done if you use just shared file hosting (like a website with FTP access only).

> Is using romcal-api the only way to achieve this?

It might (seems to), but @emagnier is more eligible to answer. But AFAIK, you still need access to the server.

**Comment by pvanthony** [comment]
> If you want to do the processing on the server, you need to use _server-side Javascript_, i.e. [Node.js](https://nodejs.org/en/). For that you need access to the server (VPS), e.g. via SSH; this cannot be done if you done if you use just shared file hosting (like a website with FTP access only).

Cool. I have ssh access. Is there any example code or documentation to use Node.js with romcal?
Sorry to ask so many questions. I am a beginner.

**Comment by tukusejssirs** [comment]
>  Sorry to ask so many questions. I am a beginner.

We all are in some stuff, no need to apologise. :wink:

---

Install Node.js (and `npm`), that depends on your server OS. I usually install it via [Node Source](https://github.com/nodesource/distributions#installation-instructions-1).

Then create a NPM project. This is not needed, but recommended. Just create an empty folder, change to it, run `npm init` and answer the questions. It creates `package.json` file.

Then install romcal via `npm i romcal`, possibly followed by a version type (see [Installation](https://github.com/romcal/romcal/#install)).

Then create a JS file in that folder. I usually add a shebang `#!/usr/bin/env node`, but it is not necessary. Note that Ubuntu might use `nodejs` as program name instead of `node`. With the shebang you can run the JS files as `./script.js` (or with absolute path) if they are executable. Without shebang use need to specify the `node` (or `nodejs`) before the program (like `node script.js`).

And see the [usage](https://github.com/romcal/romcal/#usage) for examples. I think you can leverage most of the client-side JS code with minimal modifications.

**Comment by pvanthony** [comment]
tried romcal-api and got it running. Unfortunately I am not able to get the weekday cycle. Like in https://github.com/romcal/romcal/blob/dev/docs/data-output.md#weekday-cycle

Is there a way to do the following so that the resulting array can be used any where and not inside the function only? Please note this is for using the romcal in the website like
```
        <script type="text/javascript" src="es5/vendor~romcal.bundle.es5.js"></script>
        <script type="text/javascript" src="es5/romcal.bundle.es5.js"></script>
```
Here is the array masses that I am trying to output.
```
var masses = romcal.calendarFor({
            scope: 'gregorian',
            country: 'general',
            locale: 'en',
            epiphanyOnSunday: true,
            corpusChristiOnSunday: true,
            ascensionOnSunday: false,
            outputOptionalMemorials: false,
            strictMode: true
          });
```
Then I can search in the masses array using date key for the information required.

Please note, I am not a programmer. Just trying to help my church to automate the calendar with links to the readings and reflections.

**Comment by tukusejssirs** [comment]
> tried romcal-api and got it running.

Just a note: you might be confusing [romcal-api](https://github.com/romcal/romcal-api) with [romcal](https://github.com/romcal/romcal), which are two separate things, although romcal-api depends on romcal.

As I don’t use romcal-api, my solution will be based on romcal only.

> Unfortunately I am not able to get the weekday cycle. Like in https://github.com/romcal/romcal/blob/dev/docs/data-output.md#weekday-cycle

I presume that you build romcal from source using `npm run build`, which (besides the package itself) creates a sample `dist/es5/index.html` file. If you open it in a web browser, you can see an example output with all the keys. Square brackets (`[]`) mean that it is an array and curly brackets (`{}`) designate an object (as you might already know). See bellow the first element (index 0) of the main array (i.e. `1 January`), pretiffied.

Note that if you open developer tools and your web console, you can see the same with some extra stuff, but it can be a bit confusing at first.

<details>
   <summary><code>1 January</code></summary>

```json
[
  {
    "key": "mary_mother_of_god",
    "name": "Mary, the Holy Mother of God",
    "date": "2021-01-01T00:00:00.000Z",
    "rank": "SOLEMNITY",
    "rankName": "solemnity",
    "isHolyDayOfObligation": true,
    "prioritized": true,
    "liturgicalColors": [
      "WHITE"
    ],
    "liturgicalColorNames": [
      "white"
    ],
    "seasons": [
      "CHRISTMASTIDE"
    ],
    "seasonNames": [
      "Christmastide"
    ],
    "periods": [
      "CHRISTMAS_OCTAVE",
      "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"
    ],
    "cycles": {
      "liturgicalDayCycle": "SANCTORALE",
      "sundayCycle": "YEAR_B",
      "weekdayCycle": "YEAR_1",
      "psalterWeek": "WEEK_2"
    },
    "calendar": {
      "totalWeeksInGregorianYear": 52,
      "totalWeeksInLiturgicalYear": 52,
      "weekOfGregorianYear": 53,
      "weekOfLiturgicalYear": 5,
      "weekOfSeason": 2,
      "dayOfGregorianYear": 1,
      "dayOfLiturgicalYear": 34,
      "dayOfSeason": 8,
      "dayOfWeek": 5,
      "dayOfWeekCountInMonth": 1,
      "startOfLiturgicalYear": "2020-11-29T00:00:00.000Z",
      "endOfLiturgicalYear": "2021-11-27T00:00:00.000Z",
      "easter": "2021-04-04T00:00:00.000Z"
    },
    "fromCalendar": "general",
    "fromExtendedCalendars": [],
    "metadata": {
      "titles": []
    },
    "_id": 367,
    "_stack": 1,
    "base": {
      "key": "christmas_octave_day_8",
      "name": "[8th] Day of Christmas Octave",
      "date": "2021-01-01T00:00:00.000Z",
      "rank": "WEEKDAY",
      "rankName": "weekday",
      "isHolyDayOfObligation": false,
      "prioritized": false,
      "liturgicalColors": [
        "WHITE"
      ],
      "liturgicalColorNames": [
        "white"
      ],
      "seasons": [
        "CHRISTMASTIDE"
      ],
      "seasonNames": [
        "Christmastide"
      ],
      "periods": [
        "CHRISTMAS_OCTAVE",
        "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"
      ],
      "cycles": {
        "liturgicalDayCycle": "TEMPORALE",
        "sundayCycle": "YEAR_B",
        "weekdayCycle": "YEAR_1",
        "psalterWeek": "WEEK_2"
      },
      "calendar": {
        "totalWeeksInGregorianYear": 52,
        "totalWeeksInLiturgicalYear": 52,
        "weekOfGregorianYear": 53,
        "weekOfLiturgicalYear": 5,
        "weekOfSeason": 2,
        "dayOfGregorianYear": 1,
        "dayOfLiturgicalYear": 34,
        "dayOfSeason": 8,
        "dayOfWeek": 5,
        "dayOfWeekCountInMonth": 1,
        "startOfLiturgicalYear": "2020-11-29T00:00:00.000Z",
        "endOfLiturgicalYear": "2021-11-27T00:00:00.000Z",
        "easter": "2021-04-04T00:00:00.000Z"
      },
      "fromCalendar": "general",
      "fromExtendedCalendars": [],
      "metadata": {
        "titles": []
      },
      "_id": 0,
      "_stack": 0
    }
  }
]
```

</details>

Now, you might already know how to read this object, but still I’d write it down for you:
- for the sake of this example, let’s consider that the array above is assigned to variable named `romcal`
- when you see `[]`, you can be sure that it is an array, therefore all elements in it are counted from `0` (therefore the whole thing above represents one element in the main array → `romcal[0]`);
- objects (`{}`) on the other hand can be from certain point of view considers _associative arrays_, because that contain key-value pairs, or properties, but the value can be a simple data type (like string, number, Boolean), but also an array or an object;
- if you want to access a property in an object, you place a dot with the property name, e.g. to access the `key` property (`mary_mother_of_god`), you need to write `romcal[0].key`;
- you wanted to access `weekdayCycle` cycle:
   - `cycles` property → `romcal[0].cycles`;
   - `weekdayCycle` proptery → `romcal[0].cycles.weekdayCycle`.

> Is there a way to do the following so that the resulting array can be used any where and not inside the function only?

_Not inside the function only_? If you get the data within a function, you need to `return` the object (or the variable containing the object) and ‘save’ the output of the function to a variable where you call the variable, for example (non-working code):

```js
function getData() {
   return romcal.calendarFor({})
}

const useThisVariableOutsideFunction = getData()
```

Or did you mean something else? Feel free to ask any follow-up questions. :wink:

**Comment by pvanthony** [comment]
Did the following,
```
function getData() {
   return romcal.calendarFor({
            scope: 'gregorian',
            country: 'general',
            locale: 'en',
            epiphanyOnSunday: true,
            corpusChristiOnSunday: true,
            ascensionOnSunday: false,
            outputOptionalMemorials: false,
            strictMode: true
          });
}

const useThisVariableOutsideFunction = getData();

console.log("Outside: ", useThisVariableOutsideFunction);
```
Got the following,
```
Outside: Promise { <state>: "pending" }
<state>: "fulfilled"
​<value>: Array(365) [ {…}, {…}, {…}, … ]
```
The output seem to have Promise instead of a normal array. Is there something that needs to be done? Or I should just ignore the word Promise.?

**Comment by tukusejssirs** [comment]
As romcal is running asynchronously, the function where you obtain the romcal object needs to `async` and need to `await` for romcal to generate the data.

Note that `await` cannot be used outside of an async function, but an async function can be run in synchronous function (even outside of any function, which is also run synchronously).

```js
async function getData() {
   return await romcal.calendarFor({
            scope: 'gregorian',
            country: 'general',
            locale: 'en',
            epiphanyOnSunday: true,
            corpusChristiOnSunday: true,
            ascensionOnSunday: false,
            outputOptionalMemorials: false,
            strictMode: true
          });
}

const useThisVariableOutsideFunction = getData();
```

**Comment by pvanthony** [comment]
Thank you very much for the help.
I did the code above and it shows the Promise stuff. Must be the  the rule about not working outsite an async function.

Anyway I will try again.

Once again that you for helping. I do appreciate it much.

**Comment by tukusejssirs** [comment]
Sorry, my mistake. I usually don’t load romcal directly into browser (I prefer to use Node.js).

---

1. Run the following if you already done it yet.

```bash
# Clone romcal
git clone git@github.com:romcal/romcal.git romcal  # Automatically checks out `dev` branch
cd romcal

# Install dependencies
npm ci  # Or `npm i`/`npm install`

# Build romcal
npm run build
```

2. Building romcal creates some files under `dist/` folder. You are interested in the `dist/es5/` folder, which contains `index.html` (an example) which requires `romcal.bundle.es5.js` and `vendor~romcal.bundle.es5.js` files (both are built into that very same folder).

3. Below is a modified version of the example (`index.html`), which outputs key name and weekday cycle in browser console and onto the page itself. Don’t forget to change the paths to `romcal.bundle.es5.js` and `vendor~romcal.bundle.es5.js` if necessary at the end of `<body>`.

<details>
   <summary><code>indexWeekdayCycle.html</code></summary>

```html
<!DOCTYPE html>
<html lang='en'>
<head>
  <title>Get daily weekday cycles from romcal</title>
  <meta charset='utf-8'>
</head>

<body>
  <p>
    Calendar output is:<br />
    <code id='romcal-output'></code>
  </p>

  <script>
    document.addEventListener('DOMContentLoaded', event => {
      window.romcal
      .calendarFor({
        scope: 'gregorian',
        country: 'general',
        locale: 'en',
        epiphanyOnSunday: true,
        corpusChristiOnSunday: true,
        ascensionOnSunday: false,
        outputOptionalMemorials: false,
        strictMode: true
      })
      .then(dates => {
        const romcalOutputElement = document.getElementById('romcal-output')
        dates.forEach(date => {
          // Output key name and weekday cycle to web console log
          console.log(date.key + ': ' + date.cycles.weekdayCycle)

          // Output the same data on the website
          // Note: `innerHTML` is parsed as HTML.
          romcalOutputElement.innerHTML += (date.key + ': ' + date.cycles.weekdayCycle + '<br>')
        })
      })
    })
  </script>
  <script type='text/javascript' src='vendor~romcal.bundle.es5.js'></script>
  <script type='text/javascript' src='romcal.bundle.es5.js'></script>
</body>
</html>
```

</details>

**Comment by pvanthony** [comment]
Thank you. Thank you. Thank you very much for the demo code. It has been very helpful. I will try it out.
It looks like all the code must be inside the .then(date section. Let me work on it.

Once again thank you very much for helping.

**Comment by pvanthony** [comment]
Really sorry to trouble you again. One more favour to ask. 
Trying to use the method "getDaysBefore()". Just cannot figure it out.
Getting the following error. Not sure what needs to be set.
```
Uncaught TypeError: window.romcal.calendarFor(...).getDaysBefore is not a function
```
Here is the modified code from the above example.
```
  <script>
    document.addEventListener('DOMContentLoaded', event => {
      window.romcal
      .calendarFor({
        year: 2021,
        scope: 'gregorian',
        country: 'general',
        locale: 'en',
        epiphanyOnSunday: true,
        corpusChristiOnSunday: true,
        ascensionOnSunday: false,
        outputOptionalMemorials: false,
        strictMode: true
// added the following line
      }).getDaysBefore(new Date(2024,0,1))
      .then(dates => {
        const romcalOutputElement = document.getElementById('romcal-output')
        dates.forEach(date => {
          // Output key name and weekday cycle to web console log
          console.log(date.key + ': ' + date.cycles.weekdayCycle)

          // Output the same data on the website
          // Note: `innerHTML` is parsed as HTML.
          romcalOutputElement.innerHTML += (date.key + ': ' + date.cycles.weekdayCycle + '<br>')
        })
      })
    })
  </script>
```
How to use the method "getDaysBefore()" to get three or four years at one go?

**Comment by tukusejssirs** [comment]
I have no idea why it does not work, but I presume it might only work in Node.js (@emagnier could provide more insight on this).

However, you can workaround this using basic JS code:

```js
window.romcal.calendarFor({
  year: 2021,
  scope: 'gregorian',
  country: 'general',
  locale: 'en',
  epiphanyOnSunday: true,
  corpusChristiOnSunday: true,
  ascensionOnSunday: false,
  outputOptionalMemorials: false,
  strictMode: true
})
.then (dates => {
  let testDate = new Date(2021, 0, 3)
  console.log(dates.filter(d => {
    return new Date(d.date).getTime() < testDate.getTime()
  }))
})
```

**Comment by pvanthony** [comment]
Tried the above code but it only shows dates of 2021. I think it is because of "year: 2021".

Trying to achieve an array with dates from last month to three months after last month. For example Aug 2021 to Nov 2021. Now comes the tricky part. When the current month is Nov 2021, the array should have October 2021 to January 2022. Getting the 2022 might be tough.

If these two methods can be used, getDaysBefore() and getDaysAfter(), then it should be easy to achieve, I think.

Or there is a need to create two arrays. One for 2021 and one for 2022?

**Comment by tukusejssirs** [comment]
> Tried the above code but it only shows dates of 2021. I think it is because of "year: 2021".

Oh, in my previous comment, I forget to comment on this.

Currently, you can generate only a single year, either liturgical year (from Advent of the previous year to Christ the King of the selected year) or civil year (1 Jan to 31 Dec). You cannot generate multiple years in one romcal object; for that you need to create multiple objects.

> Trying to achieve an array with dates from last month to three months after last month. For example Aug 2021 to Nov 2021. Now comes the tricky part. When the current month is Nov 2021, the array should have October 2021 to January 2022. Getting the 2022 might be tough.
> 
> If these two methods can be used, getDaysBefore() and getDaysAfter(), then it should be easy to achieve, I think.
> 
> Or there is a need to create two arrays. One for 2021 and one for 2022?

Yes, you need to generate two objects/arrays. You can check how many months there are in the current year and according to that number you’ll need to generate one or two romcal objects.

**Comment by pvanthony** [comment]
The information about creating to arrays is very helpful. Thank you for sharing that.
Once the website is up, I will try to learn the node.js way.
Thank you again for helping.

**Comment by emagnier** [comment]
The request for help appears to be addressed. 

Feel free to ask for anything else if you need to, in the new [Romcal Discussion](https://github.com/romcal/romcal/discussions) section.
