### ISSUE TITLE
Epiphany: The first day after Sunday Epiphany seems funny.

### ISSUE THREAD

**Issue by pvanthony** [pejulian/romcal#327]
Discussed in #322

**Comment by emagnier** [comment]
When Epiphany is fixed on the coming Sunday, `DAYS_BEFORE_EPIPHANY` is still outputted the day after Epiphany (e.g. in 2022).

**Comment by tukusejssirs** [comment]
On 10 January 2023, it should ~~Monday~~ Tuesday of the first week of the OT.

![Screenshot_20211117-163703_Vivaldi Browser Snapshot](https://user-images.githubusercontent.com/5111894/142231564-6c0a4fcd-cf6f-4b08-b1ff-3c88c3000164.jpg)

**Comment by pvanthony** [comment]
> On 10 January 2023, it should Monday of the first week of the OT.

I think 10th of January 2023 is a Tuesday.

**Comment by pvanthony** [comment]
Thank you very much for fixing it.
I have just compiled it and got it on the test site. Friar Julian will be looking through it before we go live with it.
Once again thank you very much for all the effort.
It's good that the fix was today as it is Friar Julian's birthday. :-)
