### ISSUE TITLE
St Agnes of Bohemia

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#33]
Add Memorial of St Agnes of Bohemia (saintAgnesOfBohemiaVirgin) to Hungarian Calendar on [8th Jun](https://en.wikipedia.org/wiki/General_Roman_Calendar#Hungary).

**Comment by pejulian** [comment]
Hi @tukusejssirs 
Here's a snippet of what I will add. 
Are the values correct?

```
    {
      "key": "saintAgnesOfBohemiaVirgin",
      "type": Types[5], // Memorial
      "moment": moment.utc({ year: year, month: 5, day: 8 }), // 8th of June
      "data": {
        "meta": {
          "liturgicalColor": LiturgicalColors.WHITE // What is the Liturgical color for this?
        }
      }
    },
```

**Comment by pejulian** [comment]
*Update*

By adding the above feast on that date to the Hungarian national calendar, it will replace:

```
{
      "key": "blessedIstvanSandorMartyr",
      "type": Types[6],
      "moment": moment.utc({ year: year, month: 5, day: 8 }),
      "data": {
        "meta": {
          "titles": [
            Titles.MARTYR
          ]
        }
      }
    }
```

However, as I see in the link provided, this feast now exists in a Congregational calendar. Therefore, it should not be a problem to move this feast out in favor of the memorial of Saint Agnes.

**Comment by tukusejssirs** [comment]
I’ve found online Hungarian Directory (liturgical calendar) for years 2017 and 2018; here is the translation of important parts:

[8th Jun 2017](https://issuu.com/malezi/docs/2017_vagoel_nelkul)
Feria or St Agnes of Bohemia (literally: of Prague), Memorial (e stands for emleknap, Memorial)
zöld = green (for Feria)
fehér = white (for St Agnes)

[8 Jun 2018](https://issuu.com/malezi/docs/dir-2018_jav-2017.11.06)
Solemnity of Sacred Heart of Jesus
White liturgical colour
[last line:] Optional Memorial of St Agnes of Bohemia is this year omited [i.e. not celebrated].


And for Bl Stephan, I have not found him neither in the Directories mentioned above nor on wiki. I think it is safe to remove it.
