### ISSUE TITLE
Rename `key` to `id`

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#373]
I think we should rename `key` (l10n key name) to `id`.

**Comment by tukusejssirs** [comment]
@emagnier, what are your thoughts?

**Comment by emagnier** [comment]
What is the motivation behind that ?

And it's not only for l10n, but also for liturgical day, calendar, martyrology items...

**Comment by tukusejssirs** [comment]
I understand it is used everywhere in romcal. :wink:

The reasoning is that IMHO `id` more widely used (in general). Also `id` (standing for _identifier_) better describes what its value means and how it is used in romcal. `key` is kind of not standard way to describe such stuff and is less descriptive than `id`.

**Comment by emagnier** [comment]
I agree to change them to `id`.
