### ISSUE TITLE
Calendar metadata: `weekOfSeason` not computed correctly for timezones that have greater offset from UTC

### ISSUE THREAD

**Issue by emagnier** [pejulian/romcal#386]
Related: #384

---

romcal fails to calculate correct `weekOfSeason` when the locale timezone has greater ofset from UTC. In romcal, we should always use UTC timezone (via `Date.prototype.getUTC*()` methods), regardless of the local timezone.

Note: Originally, adding a complete test coverage for all calendar metadata was part of this issue, however, that was moved to a separate issue (#398).

**Comment by tukusejssirs** [comment]
@emagnier, what’s the bug? Is [this](https://github.com/romcal/romcal/discussions/384#discussioncomment-3863574) wrong?

As for the tests, they’re indeed needed.

**Comment by tukusejssirs** [comment]
@emagnier, to further prove that this is _not_ an issue (apart from missing tests), I have created following (quick) test. I manually created:
- an array of all dates of Ordinary Time in 2022;
- an array of all expected `weekOfSeason` values that correspond to the array of dates.

Then I simply compare the expected values to the values computed by romcal. They all match.

```js
const Romcal = require('romcal')
const {Slovakia_En} = require('@romcal/calendar.slovakia')
const r = new Romcal({localizedCalendar: Slovakia_En})

const testAllOrdinaryDays = [
	'2022-01-10', '2022-01-11', '2022-01-12', '2022-01-13', '2022-01-14', '2022-01-15',
	'2022-01-16', '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20', '2022-01-21', '2022-01-22',
	'2022-01-23', '2022-01-24', '2022-01-25', '2022-01-26', '2022-01-27', '2022-01-28', '2022-01-29',
	'2022-01-30', '2022-01-31', '2022-02-01', '2022-02-02', '2022-02-03', '2022-02-04', '2022-02-05',
	'2022-02-06', '2022-02-07', '2022-02-08', '2022-02-09', '2022-02-10', '2022-02-11', '2022-02-12',
	'2022-02-13', '2022-02-14', '2022-02-15', '2022-02-16', '2022-02-17', '2022-02-18', '2022-02-19',
	'2022-02-20', '2022-02-21', '2022-02-22', '2022-02-23', '2022-02-24', '2022-02-25', '2022-02-26',
	'2022-02-27', '2022-02-28', '2022-03-01',
	'2022-06-06', '2022-06-07', '2022-06-08', '2022-06-09', '2022-06-10', '2022-06-11',
	'2022-06-12', '2022-06-13', '2022-06-14', '2022-06-15', '2022-06-16', '2022-06-17', '2022-06-18',
	'2022-06-19', '2022-06-20', '2022-06-21', '2022-06-22', '2022-06-23', '2022-06-24', '2022-06-25',
	'2022-06-26', '2022-06-27', '2022-06-28', '2022-06-29', '2022-06-30', '2022-07-01', '2022-07-02',
	'2022-07-03', '2022-07-04', '2022-07-05', '2022-07-06', '2022-07-07', '2022-07-08', '2022-07-09',
	'2022-07-10', '2022-07-11', '2022-07-12', '2022-07-13', '2022-07-14', '2022-07-15', '2022-07-16',
	'2022-07-17', '2022-07-18', '2022-07-19', '2022-07-20', '2022-07-21', '2022-07-22', '2022-07-23',
	'2022-07-24', '2022-07-25', '2022-07-26', '2022-07-27', '2022-07-28', '2022-07-29', '2022-07-30',
	'2022-07-31', '2022-08-01', '2022-08-02', '2022-08-03', '2022-08-04', '2022-08-05', '2022-08-06',
	'2022-08-07', '2022-08-08', '2022-08-09', '2022-08-10', '2022-08-11', '2022-08-12', '2022-08-13',
	'2022-08-14', '2022-08-15', '2022-08-16', '2022-08-17', '2022-08-18', '2022-08-19', '2022-08-20',
	'2022-08-21', '2022-08-22', '2022-08-23', '2022-08-24', '2022-08-25', '2022-08-26', '2022-08-27',
	'2022-08-28', '2022-08-29', '2022-08-30', '2022-08-31', '2022-09-01', '2022-09-02', '2022-09-03',
	'2022-09-04', '2022-09-05', '2022-09-06', '2022-09-07', '2022-09-08', '2022-09-09', '2022-09-10',
	'2022-09-11', '2022-09-12', '2022-09-13', '2022-09-14', '2022-09-15', '2022-09-16', '2022-09-17',
	'2022-09-18', '2022-09-19', '2022-09-20', '2022-09-21', '2022-09-22', '2022-09-23', '2022-09-24',
	'2022-09-25', '2022-09-26', '2022-09-27', '2022-09-28', '2022-09-29', '2022-09-30', '2022-10-01',
	'2022-10-02', '2022-10-03', '2022-10-04', '2022-10-05', '2022-10-06', '2022-10-07', '2022-10-08',
	'2022-10-09', '2022-10-10', '2022-10-11', '2022-10-12', '2022-10-13', '2022-10-14', '2022-10-15',
	'2022-10-16', '2022-10-17', '2022-10-18', '2022-10-19', '2022-10-20', '2022-10-21', '2022-10-22',
	'2022-10-23', '2022-10-24', '2022-10-25', '2022-10-26', '2022-10-27', '2022-10-28', '2022-10-29',
	'2022-10-30', '2022-10-31', '2022-11-01', '2022-11-02', '2022-11-03', '2022-11-04', '2022-11-05',
	'2022-11-06', '2022-11-07', '2022-11-08', '2022-11-09', '2022-11-10', '2022-11-11', '2022-11-12',
	'2022-11-13', '2022-11-14', '2022-11-15', '2022-11-16', '2022-11-17', '2022-11-18', '2022-11-19',
	'2022-11-20', '2022-11-21', '2022-11-22', '2022-11-23', '2022-11-24', '2022-11-25', '2022-11-26'
]

const expectedAllWeekOfSeason = [
  1, 1, 1, 1, 1, 1,
  2, 2, 2, 2, 2, 2, 2,
  3, 3, 3, 3, 3, 3, 3,
  4, 4, 4, 4, 4, 4, 4,
  5, 5, 5, 5, 5, 5, 5,
  6, 6, 6, 6, 6, 6, 6,
  7, 7, 7, 7, 7, 7, 7,
  8, 8, 8,
  10, 10, 10, 10, 10, 10,
  11, 11, 11, 11, 11, 11, 11,
  12, 12, 12, 12, 12, 12, 12,
  13, 13, 13, 13, 13, 13, 13,
  14, 14, 14, 14, 14, 14, 14,
  15, 15, 15, 15, 15, 15, 15,
  16, 16, 16, 16, 16, 16, 16,
  17, 17, 17, 17, 17, 17, 17,
  18, 18, 18, 18, 18, 18, 18,
  19, 19, 19, 19, 19, 19, 19,
  20, 20, 20, 20, 20, 20, 20,
  21, 21, 21, 21, 21, 21, 21,
  22, 22, 22, 22, 22, 22, 22,
  23, 23, 23, 23, 23, 23, 23,
  24, 24, 24, 24, 24, 24, 24,
  25, 25, 25, 25, 25, 25, 25,
  26, 26, 26, 26, 26, 26, 26,
  27, 27, 27, 27, 27, 27, 27,
  28, 28, 28, 28, 28, 28, 28,
  29, 29, 29, 29, 29, 29, 29,
  30, 30, 30, 30, 30, 30, 30,
  31, 31, 31, 31, 31, 31, 31,
  32, 32, 32, 32, 32, 32, 32,
  33, 33, 33, 33, 33, 33, 33,
  34, 34, 34, 34, 34, 34, 34
]

r.generateCalendar(2022).then(i => {
  // Filter all Ordinary days
  const daysAll = Object.entries(i).reduce((p, c, cIdx, a) => testAllOrdinaryDays.includes(c[0]) ? {...p, [c[0]]: c[1]} : p, {})

  // Test all Ordinary days
  Object.entries(daysAll).forEach((i, idx) => {
    const result = i[1][0].calendar.weekOfSeason === expectedAllWeekOfSeason[idx]
    console.log(`${i[0]} : ${result}${!result ? ` [a:${i[1][0].calendar.weekOfSeason} === e:${expectedAllWeekOfSeason[idx]}]` : ''}`)
  })
})
```

**Comment by greenars-sftwr** [comment]
I tried it without use localizedCalendar. (Like @tukusejssirs used const {Slovakia_En} = require('@romcal/calendar.slovakia') )

This is the entire code of test
```
import Romcal from 'romcal';

export default function Tests() {

  const romcal = new Romcal({
    scope: 'liturgical',
  });

  romcal.generateCalendar(2022).then((data1) => {
    
    console.log("2022-09-25",data1["2022-09-25"][0]["calendar"]["weekOfSeason"]); 
    console.log("2022-09-26",data1["2022-09-26"][0]["calendar"]["weekOfSeason"]); 
    console.log("2022-09-27",data1["2022-09-27"][0]["calendar"]["weekOfSeason"]); 
    console.log("2022-09-28",data1["2022-09-28"][0]["calendar"]["weekOfSeason"]); 
    console.log("2022-09-29",data1["2022-09-29"][0]["calendar"]["weekOfSeason"]); 
    console.log("2022-09-30",data1["2022-09-30"][0]["calendar"]["weekOfSeason"]); 
    console.log("2022-10-01",data1["2022-10-01"][0]["calendar"]["weekOfSeason"]); 
  });

  //RESULT FOR "weekOfSeason"
  // 25, 26, 26, 26 ,26, 26, 26


  return (
    <div>tests</div>
  );
}
```

The result in console log shows 25 in weekOfSeason for 2022-09-25.

**Comment by tukusejssirs** [comment]
@jctc06, well, I tested the code in plain JavaScript (`.cjs`) and ESM (`.mjs`), however, always via Node.js. Now, you seem to run it in the browser (in you latest code example, you return `<div>tests</div>`). I have just tested it out in the browser (using `unpkg.com` to source romcal) and it works as expected. Below is the code I used

<details>
   <summary><code>romcal.html</code></summary>

```html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='UTF-8' />
    <title>romcal test</title>
    <script src='https://unpkg.com/romcal@3.0.0-dev.14/dist/iife/romcal.js'></script>
  </head>
  <body>
    <h1>romcal v3</h1>
    <hr>
    <p>Open the developer tools and check the console.</p>
    <script>
      const romcal = new Romcal({scope: 'liturgical'})
      // const romcal = new Romcal()

      romcal.generateCalendar(2022).then((data1) => {
        console.log('2022-09-25', data1['2022-09-25'][0]['calendar']['weekOfSeason'])
        console.log('2022-09-26', data1['2022-09-26'][0]['calendar']['weekOfSeason'])
        console.log('2022-09-27', data1['2022-09-27'][0]['calendar']['weekOfSeason'])
        console.log('2022-09-28', data1['2022-09-28'][0]['calendar']['weekOfSeason'])
        console.log('2022-09-29', data1['2022-09-29'][0]['calendar']['weekOfSeason'])
        console.log('2022-09-30', data1['2022-09-30'][0]['calendar']['weekOfSeason'])
        console.log('2022-10-01', data1['2022-10-01'][0]['calendar']['weekOfSeason'])
      });
    </script>
  </body>
</html>
```

</details>

Your latest code works for me as expected in `.mjs` (all `weekOfSeason` values are `26`). All I modified is to comment out lines 3, and 24-27 (move the code out of the function), which should not affect the romcal output.

```js
import Romcal from 'romcal'

const romcal = new Romcal({scope: 'liturgical'})

romcal.generateCalendar(2022).then((data1) => {
  console.log('2022-09-25', data1['2022-09-25'][0]['calendar']['weekOfSeason'])
  console.log('2022-09-26', data1['2022-09-26'][0]['calendar']['weekOfSeason'])
  console.log('2022-09-27', data1['2022-09-27'][0]['calendar']['weekOfSeason'])
  console.log('2022-09-28', data1['2022-09-28'][0]['calendar']['weekOfSeason'])
  console.log('2022-09-29', data1['2022-09-29'][0]['calendar']['weekOfSeason'])
  console.log('2022-09-30', data1['2022-09-30'][0]['calendar']['weekOfSeason'])
  console.log('2022-10-01', data1['2022-10-01'][0]['calendar']['weekOfSeason'])
});
```

I’d like to emphasise that for me it works as expected regardless of `scope` value (`liturgical` or `gregorian`) and if I specify a locale or particular calendar. For me it always works.

I’d like to know if you test this againts `dev` branch (445ca5a) or version `3.0.0-dev.14` (both output the same code). I haven’t test older commits/versions. Could you check what romcal version you use please? The easiest way is to run `console.log(Romcal.getVersion())` which should output `3.0.0-dev.14` or similar.

---

**Update**

I have created some online reproductions:

- browser version of your latest code at [JSFiddle](https://jsfiddle.net/tukusejssirs/4e1j9xdt/13/) (I used `unpkg.com` to source romcal);
- Node.js module (ESM in JS) at [runkit.com](https://replit.com/@tukusejssirs/romcaltestjsesm#index.js);
- Node.js CJS (CJS in JS) at [runkit.com](https://replit.com/@tukusejssirs/romcaltestjsesm#index.js).

**Comment by greenars-sftwr** [comment]
@tukusejssirs , Thank you for your answer.,

The version output is `3.0.0-dev.14`. I installed it using `npm install romcal@dev`.

I see the tests in Node, but I cant run your JSFiddle. 
```
Uncaught ReferenceError: Romcal is not defined
    at ?editor_console=:119:16
```

I am trying to see my code more deeper trying to find why I still having this error.
I give you another info about my code: 

React JS 18.2.0
Romcal 3.0.0-dev.14
Node v18.11.0

I have no experience publishing in JSFiddle, but I going to try.

**Comment by greenars-sftwr** [comment]
I uploaded a github repo with just Romcal. 

You can find it here:
https://github.com/jctc06/romcaltest1

This repository was created by following these steps in the terminal
```
1. Create App: `npx create-react-app romcaltest1 --template typescript`
2. Install Romcal: `npm install romcal@dev`
3. Execute app: `npm start`
```

The test code is already in `/src/App.tsx`

**Comment by tukusejssirs** [comment]
> I see the tests in Node, but I cant run your JSFiddle.

I fixed it in [here](https://jsfiddle.net/tukusejssirs/4e1j9xdt/13/). I always updated the link in my previous comment.

> You can find it here: https://github.com/jctc06/romcaltest1

It works for me. :man_shrugging:

![image](https://user-images.githubusercontent.com/5111894/196215333-d2b68bed-f315-4d4f-8086-52044ff1b631.png)

**Comment by greenars-sftwr** [comment]
Sorry @tukusejssirs I am writting in the 2 conversations (Discussions and Issues) If you agree, we can continue here. 

My last Question there was. 
Related with this: I am thinking that maybe the problem is related with my location (America / Bogotá - Colombia).

I share with you a screenshot of the same code, without any modification. 
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/47371528/196220007-a9fa35fe-b1b9-49c3-90f0-8392863e33b6.png">

I tested your JSFiddle, here is a Screenshot. 
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/47371528/196221486-45dbb2fe-f0e6-485c-a001-d33cecb2b0b3.png">

**Comment by tukusejssirs** [comment]
Thanks, @jctc06! Indeed I can reproduce this issue when I change the timezone (I updated [JSFiddle](https://jsfiddle.net/tukusejssirs/4e1j9xdt/15/) to output the local timezone).

A quick workaround is to use set timezone to `UTC`, however, ATM I have no idea how to accomplish this globally in the browser without changing the actual browser timezone. In terminal/command-line, it is quite easy to accomplish: set `TZ` env variable to `UTC`.

@emagnier, would changing the timezone of `date` to `UTC` after [`lib/models/calendar.ts` (L36)](https://github.com/romcal/romcal/blob/dev/lib/models/calendar.ts#L36)? Or how would you solve this issue? Maybe we should change how romcal treats dates and calculate in the local (browser) timezone.

**Comment by tukusejssirs** [comment]
@emagnier, `TZ='America/Bogota' npm run test` fails 6 test suites and 84 tests.

I tried to fix this by using `Date.prototype.getUTC*()` methods (e.g. `getUTCDay()`), however, it didn’t fix the issue.

**Update:** Actually, using `getUTC*()` methods seems to work, but I had to change it everywhere in romcal (even in `tests/`). Now both `npm run test` and `TZ='America/Bogota' npm run test` succeeds.

**Comment by tukusejssirs** [comment]
@jctc06, I think I fixed the issue, however, I still need to create a PR for it. Could you test out [this commit](https://github.com/tukusejssirs/romcal/tree/week_of_season_issue_384) (`week_of_season_issue_384` branch in my fork)? Simply run `npm ci && npm run build` and use the files inside `dist/` in your app.
