### ISSUE TITLE
Remove old, unused branches

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#392]
I suggest to remove branchees that are not used anymore:

- `commit-xp`;
- `gh-pages`;
- `master`;
- `test`.

**Comment by tukusejssirs** [comment]
Just a note: I can’t do this myself, as I have no permission to do so. :wink:

**Comment by emagnier** [comment]
I made the cleanup.

We need to keep `master`, as the current stable npm release (1.3.0) is still based on it.
