### ISSUE TITLE
When a memorial in the general calendar is moved in the national calendar

### ISSUE THREAD

**Issue by djanulew** [pejulian/romcal#4]
If you generate a calendar for Canada.  The feast of Saints Jean de Breubef... appears twice.  Once on the correct date of Sept 26, and then again on the universal day of Oct 19 as an optional memorial.  It should not appear the second time.

great work.

Fr. Daniel

**Comment by pejulian** [comment]
Hi Fr. @djanulew,

Thank you for your feedback!

I have added a fix for this problem (ensure that only 1 key is used to identify the feast in question).
Also, a specific locale file for the Canadian calendar has been added (en-ca). 
It can used to define further specifics of the Canadian liturgical calendar.

The output for the Canadian calendar can be obtained as follows:

```
Romcal.calendarFor({
     year: 2017,
     country: 'canada',
     locale: 'en-ca'
});
```
