### ISSUE TITLE
Not able to get  localized translations for pt-br, en-gb, en-ie

### ISSUE THREAD

**Issue by LagoonProject** [pejulian/romcal#423]
Hi,

I'm new to romcal and trying to implement it in my app, it works fine overall but I can't get it to output the localized translations for the following locales : pt-br, en-gb, en-ie.

I tried to run the react-app from the examples folder locally and I get the same problem.

Here are the steps to reproduce:

`cd .\react-app\`

change package.json to avoid an error with node 18 (Error: error:0308010C:digital envelope routines::unsupported).
 
```
"scripts": {
    "start": "react-scripts --openssl-legacy-provider start"
...
}
```

then 

`yarn`

then 

`yarn start`

I see the romcal app in the browser, if I select any locale from the dropdown like en, fr, es, cs, it... it works fine:

![romcal_es](https://user-images.githubusercontent.com/42693834/222286925-ba45a9f7-eb18-42c1-b8ec-e85cd2b981f7.jpg)

But if I select  pt-br, en-gb or en-ie, I don't have the translations no matter the calendar selected:

![romcal_pt](https://user-images.githubusercontent.com/42693834/222286837-9bfcc182-b4b4-4f49-94ec-1fb26d09d54a.jpg)

Do you have any idea where it comes from?

Any help would be much appreciated.

**Comment by emagnier** [comment]
Hello @LagoonProject! There is indeed a bug with locales composed with a dash (`-`). Thank you for reporting it! 
I'll try to fix it in the following days.

**Comment by LagoonProject** [comment]
> Hello @LagoonProject! There is indeed a bug with locales composed with a dash (`-`). Thank you for reporting it! I'll try to fix it in the following days.

Thanks for your answer. I'm glad you identified the problem. I'll wait for the update then.

**Comment by emagnier** [comment]
@LagoonProject, FYI this bug is now fixed. You have to upgrade romcal + all romcal dependencies to at least `3.0.0-dev.32`.

And thank you for mentioning the now required `--openssl-legacy-provider` flag (to start the react app example). I'll also update the romcal examples as soon as I can 👍

**Comment by LagoonProject** [comment]
> @LagoonProject, FYI this bug is now fixed. You have to upgrade romcal + all romcal dependencies to at least `3.0.0-dev.32`.
> 
> And thank you for mentioning the now required `--openssl-legacy-provider` flag (to start the react app example). I'll also update the romcal examples as soon as I can 👍

Thanks for the fast update. I should be able to test it very soon. 

BTW you guys did an amazing job with romcal, very useful library that addresses a complex topic in a convenient way, I imagine a lot of work was put into it, congrats!
