### ISSUE TITLE
unable to build source code

### ISSUE THREAD

**Issue by LagoonProject** [pejulian/romcal#425]
Hi,

I'm trying to build romcal locally on a windows 10 PC to see if I can add some translations to the locales files.
However it starts to build then fails.

I'm on node v18.12.1.

I don't have much experience in dev, here's the steps I follow:

`git clone git@github.com:romcal/romcal.git
`
`cd romcal/
`
`npm install
`
`npm run build
`

Then it starts building but fails with the following error:

![romcal_build_error](https://user-images.githubusercontent.com/42693834/224558615-fc9eb9b7-1ce3-4b7a-9d87-e782cbf10ada.PNG)

It looks like [calendar] is undefined, I don't know if I'm doing something wrong, any help would be appreciated.

Thanks.

**Comment by tukusejssirs** [comment]
It works on Linux with `npm@9.1.2` and `node@19.7.0`. I haven’t tested it on MS Windows though.

> ```bash
> X [ERROR] Failed to create output directory: mkdir `G:\dev\romcal\dist\hundles\undefined\cjs\G:: Laxyntaxe du nom de fichier, de répertoire ou de volume est incorrecte.
> ```

Now, here I see two issues:
1. `G:\dev\romcal\dist\bundles\undefined` is invalid path because `undefined/` folder should not be created either;
2. `G:\dev\romcal\dist\hundles\undefined\cjs\G:` is invalid path on MS Windows, as a file/folder name cannot contain a colon (`:`), but the final file/folder is `G:`, which is invalid. This looks like an error in the build script IMHO.

I presume you have not made any change to the source code before building.

Anyway, I want to test this on MS Win 10. I want to do this today (CST/UTC+01 timezone).

PS—In future, could you copy-paste the output and use [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) instead of adding a screenshot please? Thanks! :pray:

**Comment by tukusejssirs** [comment]
Okay, I have found the issue and fixed it (see PR #426). You can test the PR.

**Comment by LagoonProject** [comment]
Hi @tukusejssirs , thanks for your fast answer and sorry for the screenshot.

I pasted your change in build.ts at line 218 :

`        (format !== 'iife' || !/[\\/]index\.ts$/.exec(p)) &&
`


but unfortunately I get the same error when trying to build:

```
$ npm run build

> romcal@3.0.0-dev.32 prebuild
> npm run lint


> romcal@3.0.0-dev.32 lint
> eslint . --ext .ts      


> romcal@3.0.0-dev.32 build
> node -r ts-node/register scripts/build.ts


  –– Romcal builder ––

✓ Write constants into ./tmp/constants/, to list available calendars and locales
  ./tmp/constants/locales.ts
  ./tmp/constants/calendars.ts

✓ Compiling sources and checking types of the romcal library
  .d.ts files created in ./tmp/dts/

✓ Generate calendar bundle files into ./tmp/bundles/
  generated 60 calendars in 11 locales in ./tmp/bundles/

✓ Cleaning up the ./dist/ directory

✓ Bundle all .d.ts files into ./dist/index.d.ts
  ./tmp/dts/lib/index.d.ts → dist/index.d.ts

✓ Building the codebase using the cjs format
  ./lib/index.ts → dist/cjs/romcal.js
  ./tmp/bundles/**/*.ts → dist/bundles/[calendar]/cjs/[locale].js
X [ERROR] Failed to create output directory: mkdir G:\dev\romcal\dist\bundles\undefined\cjs\G:: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte.
```


Is there something else to do?
Otherwise I have not changed the source code.

**Comment by tukusejssirs** [comment]
There are three lines changes and you copied the least important (but still important) one. Check the two lines below my PR comment (L221-222). :wink:

Anyway, the simplest way to test it is to clone [my fork (`build_on_win` branch)](https://github.com/tukusejssirs/romcal/tree/build_on_win).

**Comment by LagoonProject** [comment]
> There are three lines changes and you copied the least important (but still important) one. Check the two lines below my PR comment (L221-222). 😉
> 
> Anyway, the simplest way to test it is to clone [my fork (`build_on_win` branch)](https://github.com/tukusejssirs/romcal/tree/build_on_win).

Thanks you so much @tukusejssirs !! I missed the other lines my apologies.

It works now and builds successfully:

```
$ npm run build

> romcal@3.0.0-dev.32 prebuild
> npm run lint


> romcal@3.0.0-dev.32 lint
> eslint . --ext .ts


> romcal@3.0.0-dev.32 build
> node -r ts-node/register scripts/build.ts


  –– Romcal builder ––

✓ Write constants into ./tmp/constants/, to list available calendars and locales
  ./tmp/constants/locales.ts
  ./tmp/constants/calendars.ts

✓ Compiling sources and checking types of the romcal library
  .d.ts files created in ./tmp/dts/

✓ Generate calendar bundle files into ./tmp/bundles/
  generated 60 calendars in 11 locales in ./tmp/bundles/

✓ Cleaning up the ./dist/ directory

✓ Bundle all .d.ts files into ./dist/index.d.ts
  ./tmp/dts/lib/index.d.ts → dist/index.d.ts

✓ Building the codebase using the cjs format
  ./lib/index.ts → dist/cjs/romcal.js
  ./tmp/bundles/**/*.ts → dist/bundles/[calendar]/cjs/[locale].js

✓ Building the codebase using the esm format
  ./lib/index.ts → dist/esm/romcal.js
  ./tmp/bundles/**/*.ts → dist/bundles/[calendar]/esm/[locale].js

✓ Building the codebase using the iife format
  ./lib/index.ts → dist/iife/romcal.js
  ./tmp/bundles/**/*.ts → dist/bundles/[calendar]/iife/[locale].js

✓ Package calendar bundles as npm modules
  created 60 modules in ./dist/bundles/
  created ./package.json to each modules
  /tmp/bundles/[calendar]/index.d.ts → dist/bundles/[calendar]/index.d.ts

✨ Done in 59.305s
```

Thanks for your help. I'm going to close issue now.

**Comment by tukusejssirs** [comment]
Don’t close the issue until it is merged into `dev` branch in this repo, thanks. :wink:

**Comment by LagoonProject** [comment]
ok, sorry. I let you guys close the issue then.
Cheers.

**Comment by tukusejssirs** [comment]
@LagoonProject, `romcal@3.0.0-dev.33` is now being released. It will contain the fix for building romcal on MS Windows.
