### ISSUE TITLE
Not an issue - Question about translations and pull request process

### ISSUE THREAD

**Issue by LagoonProject** [pejulian/romcal#429]
Hi,

I would like to try to provide some translations for the locales in Spanish and Portuguese, as I see there's quite some days that the name entry falls back in english.

What are the files that should be updated? I see in the locales folder there is es.ts and pt-br.ts, Is there something else to update?

My idea is to take some keys in general-calendar > proper-of-saints.ts and also in some particular-calendars that are not in es.ts and pt-br.ts and see if I can provide the translation. Is that the right thing to do?

Should I paste the new entries below the existing ones so it's easier for review or should I respect the alphabetical order?

Is there anything else to do for the pull request of translations?

Thanks.

**Comment by emagnier** [comment]
Hello @LagoonProject! 

Thank you for offering your help on the Spanish and Portuguese translations, you are more than welcome to help us on this project!

Romcal 3.x ins't released yet, and there is still unfortunately a lack of documentation, contribution tutorials, and tooling to provide easy ways to bootstrap & check locales and calendar data... 

But indeed, as you see, there are already some locale files that could be improved/completed:
- `lib/locales/es.ts`
- `lib/locales/pt-br.ts`
If you are only working on translation, this should be the only 2 files you should have to edit.

FYI, the English locale (`en.ts`) should contain everything localized. So if you see that something is missing, you can have a look at the English locale file to have an example.

And it's better to keep the alphabetical order. Reviewing them in GitHub will not be a problem.

Thank again!
