### ISSUE TITLE
Fix transfer of `joseph_spouse_of_mary` in `slovakia.ts`

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#432]
I have just noticed that `joseph_spouse_of_mary` is not transfered this year to Monday 20 Mar 2023 in `slovakia.ts`. It works as expected in GRC.

https://github.com/romcal/romcal/blob/5d3fc9c7be367bbb679bbcf63479a4db5e461241/lib/general-calendar/proper-of-saints.ts#L218-L234

https://github.com/romcal/romcal/blob/5d3fc9c7be367bbb679bbcf63479a4db5e461241/lib/particular-calendars/slovakia.ts#L21-L23

I think adding `dateExceptions` to `slovakia.ts` would work this issue around, but I think this needs to be fixed more deeply.

I believe this issues comes from the fact that `joseph_spouse_of_mary` is not a solemnity in Slovakia. I think that each holy day of obligation defined in the GRC should be transfered to the same date when necessary, regardless if that celebration is a HDO in a particular calendar or not.

**Comment by emagnier** [comment]
It looks like a bug. When the date is computed, `joseph_spouse_of_mary` from the Slovakia calendar should include on all properties already defined in the General Roman calendar.
