### ISSUE TITLE
Add `optional memorial` rank

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#435]
I have just noticed that there is no optional memorial in l10n files.

https://github.com/romcal/romcal/blob/5d3fc9c7be367bbb679bbcf63479a4db5e461241/lib/locales/en.ts#L54-L60

While the rank of a celebration in calendar files is defined using `Precedences.OptionalMemorial_12`, but in the output of romcal we need get `MEMORIAL` rank, `OPTIONAL_MEMORIAL_12` precedence, `isOptional` set to `true` and `rankName` is set to `memorial`.

```js
// Example
{
    id: 'most_holy_name_of_jesus',
    date: '2023-01-03',
    dateDef: { month: 1, date: 3 },
    precedence: 'OPTIONAL_MEMORIAL_12',
    rank: 'MEMORIAL',
    allowSimilarRankItems: false,
    isHolyDayOfObligation: false,
    isOptional: true,
    ...
}
```

Now, I think we should treat optional memorial rank as a different one from obligatory memorial, at the very least from the l10n point of view, as we should return different `rank` string.

While I get it that `isOptional` makes sense from one point of view, it does not make sense from l10n point of view. Actually, I consider this a bug, as _at the very least_ `rankName` should return `optional memorial` instead of `memorial`.

**Comment by emagnier** [comment]
I agree, it creates a gap in the translation. Ok to re-introduce the `OPTIONAL_MEMORIAL` rank.
