### ISSUE TITLE
Locale definitions are incompatible with Webpack 5

### ISSUE THREAD

**Issue by ciesiolka** [pejulian/romcal#457]
Using Localization package into the TypeScript project with Webpack 5 fails with the following errors:
```
ERROR in ./node_modules/@romcal/calendar.poland/esm/index.mjs 25:0-38
Module not found: Error: Can't resolve './cs' in 'C:\Users\Mat\Documents\spiewnik-organisty\node_modules\@romcal\calendar.poland\esm'
Did you mean 'cs.mjs'?
BREAKING CHANGE: The request './cs' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains 
'"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```
The same error is repeated 12 times, one for each language.

Installed with `npm i romcal@dev @romcal/calendar.general-roman@dev @romcal/calendar.poland@dev`.

**Comment by tukusejssirs** [comment]
Could you give a MVE? This seems like you try to use ESM modules (`*.mjs` files) instead of CommonJS files (`*.js` files).

Look at these files:

```
node_modules/@romcal/calendar.general-roman/cjs/pl.js
node_modules/@romcal/calendar.general-roman/esm/pl.mjs
node_modules/@romcal/calendar.poland/cjs/pl.js
node_modules/@romcal/calendar.poland/esm/pl.mjs
node_modules/romcal/dist/cjs/romcal.js
node_modules/romcal/dist/esm/romcal.mjs
```

It might be related to you TS/Webpack configuration.

**Comment by ciesiolka** [comment]
Webpack prioritizes mjs over js by default (see https://github.com/webpack/webpack/issues/5756) and in Webpack 5 a breaking change was introduced which makes the `.mjs` extension mandatory, unless the whole project is marked as module (see similar issue https://github.com/babel/babel/issues/12169).

I'll try to prepare MVE tomorrow.

**Comment by TobiTenno** [comment]
@ciesiolka this should theoretically be fixed now, with some of the explicit exports added in dev.57. I'd love to collab with you if you need any help with an extra set of eyes

**Comment by TobiTenno** [comment]
I can confirm this is working on at latest dev.60, if not earlier, as we're webpack 5 using on romcal-examples/react-app (see romcal/romcal-examples#2)

**Comment by TobiTenno** [comment]
i'll close this out next week if we don't hear back from you, @ciesiolka

**Comment by TobiTenno** [comment]
closing, per above
