### ISSUE TITLE
21 January - spanish locale missing week number - third sunday ordinay time

### ISSUE THREAD

**Issue by miguelms95** [pejulian/romcal#474]
Hi, 21 january, there is no translation or mapping for the third sunday of Ordinary time. Romcal returns {{week}}, see below:
<img width="464" alt="image" src="https://github.com/romcal/romcal/assets/17082987/c0dd1720-231c-451f-a19c-d216e2402a0c">

i'm not sure where to update to solve this.

**Comment by miguelms95** [comment]
Ok, i see that the value is here: https://github.com/romcal/romcal/blob/dev/lib/locales/es.ts#L561C5-L561C30 but not replaced 🤔. Maybe it can be subtituted with only "Domingo de la Palabra de Dios"? @emagnier

**Comment by tukusejssirs** [comment]
@miguelms95, thanks for the report! :pray:

Indeed, there is a bug. It should be done using `$t(ordinals:{{week}})`, as it is done in `en.ts` (see below).

https://github.com/romcal/romcal/blob/5e6dec4a3baa2f09f179b9938894cc42596bb852/lib/locales/en.ts#L9

Therefore, the value of the key should be replaced with `$t(ordinals:{{week}})º domingo del Tiempo Ordinario, o domingo de la Palabra de Dios`.

I’ll fix it, as it seems like there are other places where the same bug needs to be fixed.

**Comment by miguelms95** [comment]
You're welcome, @tukusejssirs! Also share with you a PR with some little fixes for spanish localization: https://github.com/romcal/romcal/pull/475

If you want me to make a PR with `$t(ordinals:{{week}})` fix in spanish localization let me know, and I can append to that PR (or open a new one)

**Comment by tukusejssirs** [comment]
> Also share with you a PR with some little fixes for spanish localization: https://github.com/romcal/romcal/pull/475

Thanks, @miguelms95! :pray: I’ve seen it, but to be honest, I’m extra busy this January, however, I’ll try to find some time to review it (possibly next weekend).

> If you want me to make a PR with $t(ordinals:{{week}}) fix in spanish localization let me know, and I can append to that PR (or open a new one)

Actually, I was wrong. I should work with `{{week}}` (`$t(ordinals:{{week}})` should print the ordinal number as word (e.g. in English: `1` → `first`), however, even that fails in this context. Moreover, `{{week}}` works in other instances (e.g. `Miércoles de la 1ª semana del Tiempo Ordinario`).

I have no time for this to debug right now, maybe @emagnier could tell us why it fails for keys in `.names`, but not for keys in `.seasons`. :thinking:

**Comment by miguelms95** [comment]
Hi @emagnier, ping about this topic :) could you review it? thanks in advance!

**Comment by tukusejssirs** [comment]
@emagnier seems to be busy at work, family and life, however, it seems like `i18next` is not configured to run the functions on keys in `.names` in l10n files.

Easy fix/workaround to this issue is to hard-code the week number (which does not actually change for the Sunday of Divine Word), however, I think that the proper fix is to run the functions on keys in `.names` too. Maybe @TobiTenno wants to look into this. :wink:

That said, I’ll create a PR to replace `{{week}}` in every locale that uses it and add a test to check if the values is correct.

**Comment by TobiTenno** [comment]
I'm down, i'll get on that this weekend.

**Comment by tukusejssirs** [comment]
Guys, I have created a PR to hard-code the seasonal week number and create a thorough test suite (maybe too thorough) in #477. @TobiTenno, could you review it please?
