### ISSUE TITLE
typo: rename file `calendars/sriLangka.js` to `calendars/sriLanka.js`

### ISSUE THREAD

**Issue by tukusejssirs** [pejulian/romcal#9]
I just found out that you misspelled the name of `calendars/sriLangka.js` file (it looks like you use a text editor / IDE that gives you completion options and you probably pressed enter and did not notice that change to `*lang*`). I think this should be fixed. :)

**Comment by pejulian** [comment]
Hi @tukusejssirs,

Thank you for pointing this out.
I have made a fix and it will be merged to `master` from the `romcal-es6` branch that I am currently working on.
